### ISSUE TITLE
Reconfigure Mann Library hours in LibCal

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#1050]
Will involve removing most of our existing departments and replacing with 1 or 2 new depts covering pickup options.

**Comment by eeh53** [comment]
I plan to work on this over the weekend. Should I let you know if I manage to take the website down again after I delete most of our hours locations? ;)

**Comment by cappadona** [comment]
You know where to find me...

**Comment by cappadona** [comment]
Tobi has reconfigured the _depts_ within Mann for LibCal hours. Thanks!
