### ISSUE TITLE
Specialty task

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#106]
#### Potential tasks

1. You need more assistance with GIS (Geospatial Information Systems). 

#### To do

- [ ] Content type for librarians (what fields? how many entries for first pass?)
- [ ] Is this bigger than **liaisons** and if so where should it live? (Tobi & Nick discussed this on Thurs 3/17)
- [ ] Figure out how we're going to manage LibGuides (direct parse of API call or do we need to add our own level of curation?)

**Comment by cappadona** [comment]
We decided to **not include** a task with this focus for the first round of testing, so moving this to the icebox for consideration for later rounds.

**Comment by cappadona** [comment]
Moving this to Baked because we need to decide how to manage our running list of potential tasks for future rounds of usability testing. More details in #108.

**Comment by eeh53** [comment]
Created new issues for LibGuide management and librarian content type, and moved this usability task to #148
