### ISSUE TITLE
Review Booked based on requirement matrix

### ISSUE THREAD

**Issue by tap87** [cul-it/mann-wagon#111]
We need to decide on a booking solution based on the [requirement matrix](https://docs.google.com/spreadsheets/d/1nq5zXXHC8r1XTVfODcq-PAs4jWFizWacZP2CLhcogPw/edit#gid=942321703), and the development effort needed to implement them.

**Comment by cappadona** [comment]
I just forked the Sourceforge Git repo for Booked (well, one of them) and have pushed it to GitHub:
https://github.com/cul-it/mann-booked

This is a fork of the [Sourceforge repo](https://sourceforge.net/p/phpscheduleit/source) being used to track the upcoming `v2.6` release. Our current test instance is running `v2.5.19`, the [latest minor version](http://www.bookedscheduler.com/whatsnew) of the stable `v2.5` release being tracked in a [separate Sourceforge repo](https://sourceforge.net/p/phpscheduleit/2.5).

If we decide to run with Booked, probably one of our first tasks will be to install a `v2.6` instance locally...

**Comment by tap87** [comment]
@cappadona I looked at the two repos, and I agree that we should use the source (v2.6). I will install it locally and see how things go.

**Comment by cappadona** [comment]
Great. Thanks. I just checked this morning and still no update on [release date for 2.6](http://php.brickhost.com/forums/index.php?topic=14592.0).

**Comment by tap87** [comment]
I have got another issue #233  for installing 2.6 locally. Baking this one.
