### ISSUE TITLE
Create a clear landing page for the types of rooms available to be reserved by both the public and staff

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#12]
https://issues.library.cornell.edu/browse/MANNWEB-126

**Comment by sew268** [comment]
![reservation workflow 2](https://cloud.githubusercontent.com/assets/14821406/12919744/7f4c5ace-cf13-11e5-9586-ee89598b0c46.jpg)
![reservation workflow](https://cloud.githubusercontent.com/assets/14821406/12919746/7f588b78-cf13-11e5-9c0d-d0e3d196e83c.jpg)
![room bookings current workflow](https://cloud.githubusercontent.com/assets/14821406/12919742/7f44315a-cf13-11e5-96d7-abe43ab37c5e.jpg)
![workflow - 100 102](https://cloud.githubusercontent.com/assets/14821406/12919747/7f596b42-cf13-11e5-820f-c5ca783b3b44.JPG)
![workflow - interview obs hive group study](https://cloud.githubusercontent.com/assets/14821406/12919743/7f4845c4-cf13-11e5-9c18-0db7fe8d0634.JPG)
![workflow - lobby](https://cloud.githubusercontent.com/assets/14821406/12919745/7f4d86ec-cf13-11e5-892e-ac286ba70bae.JPG)
![workflow - stone classroom](https://cloud.githubusercontent.com/assets/14821406/12919748/7f6d7484-cf13-11e5-9d72-941f49dc8df2.JPG)

**Comment by sew268** [comment]
[Gallery Spaces.docx](https://files.zenhub.io/56b9fe69f92eb7f93915859d)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by sew268** [comment]
[Reservation System Requirements for New System.docx](https://files.zenhub.io/56b9fe85f92eb7f9391585a1)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by sew268** [comment]
[Consultation area workflow.docx](https://files.zenhub.io/56b9feb3f92eb7f9391585ad)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by sew268** [comment]
[Room 160.docx](https://files.zenhub.io/56b9febaf92eb7f9391585b0)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by sew268** [comment]
[Reservation System Requirements GoogleDoc](https://docs.google.com/spreadsheets/d/1nq5zXXHC8r1XTVfODcq-PAs4jWFizWacZP2CLhcogPw/edit#gid=186001220)

**Comment by sew268** [comment]
[spaces landing page.pdf](https://files.zenhub.io/56bdf2f0f7471cd9688f24ab)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by sew268** [comment]
Spaces landing page on new website makes this possible
