### ISSUE TITLE
Return exception string (note) as separate field

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#132]
Need to be able to target the `note` explicitly. Currently the gem is simply [returning a concatenated string for `{{time}}`](https://github.com/cul-it/mann_liquid_extensions/blob/b54f8a40e50043a584737bb617ef93421c79a8fa/lib/mann_liquid_extensions/liquid/drops/mannlib_weekly_hours.rb#L33) as provided by the `rendered` field from the LibCal API.

**Comment by tap87** [comment]
I have updated the hours gem to render the time and note from exceptions as an array, [see commit](https://github.com/cul-it/mann_liquid_extensions/commit/31a14cde0b2f8c8dd4eb7b23194139d6ceba0415), 
time now returns an array, with time[0] for the rendered time and time[1] for the note for exceptions.
