### ISSUE TITLE
Library is always open

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#133]
It appears that `mann_liquid_extensions` is always returning `Open` for `mannlib_hours.open`. This is a tough one to test since you can't include a time in your request to the LibCal API, it assumed `now`, but let's just say that I've been working on the site quite a bit the past few weeks, and have never seen the Library closed, even clearly after regular hours.

There must be an issue with the [logic here](https://github.com/cul-it/mann_liquid_extensions/blob/b54f8a40e50043a584737bb617ef93421c79a8fa/lib/mann_liquid_extensions/liquid/drops/mannlib_hours.rb#L11,L16). Is the `status` property actually not returned if the location is closed?

##### Another suggestion to consider while addressing this bug:

Change the name of the `open` key to `isOpen` and store it as a boolean so we can avoid string comparison in the template.

**Comment by tap87** [comment]
This has been fixed in the gem repo using this [commit](https://github.com/cul-it/mann_liquid_extensions/commit/9be59af1009aa116d8c1c4fa9fe2f02e076e8144)
The status field gives general information on whether library is open or closed irrespective of the hours.
Now using currently_open field, which provides the actual status based on the current time.

**Comment by cappadona** [comment]
@tap87 Thanks, Tahir. Looks good as far as I can tell although I'll hold off on considering it *baked* until I've had a chance to verify that the Library reports the correct status after hours tonight.

> P.S. I don't think it's possible to pass a future time (greater than known closing) as part of the request to test this. The API just automatically tests against `now`, correct?

**Comment by tap87** [comment]
@cappadona There is a few ways to test it faster:

- Modify today's hours temporarily

- Modify gem api call, use department that is closed, something like GIS (lid=2204)
