### ISSUE TITLE
Upcoming events on homepage

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#134]
Split out into two groupings, each with next X (3 or 4?) items, respectively:

1. Events & Exhibits
1. Workshops & Classes

Both will require merged data from CU Events Calendar (Localist) and new Mann reservation system ([most likely Booked](https://github.com/cul-it/mann-wagon/issues/111)).

> This is a natural extension of the work being done for the events page in #110, #35

**Comment by cappadona** [comment]
Hey Tahir, does this include the ability to link to a filtered view of the events, which would cover the functionality of the **All Workshops &amp; Classes &raquo;** link?

**Comment by tap87** [comment]
No, you can't link to the filter's directly, yet. I need to think about how that is going to work in our setup.

**Comment by tap87** [comment]
You beat me to it, I was just working on creating the same issue. Thanks.
