### ISSUE TITLE
Populate use/computing of dev site

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#138]
Including children pages `use/computing/desktops`, `use/computing/laptops`.

**Comment by sew268** [comment]
I think I've populated these as best I can.  We'll need to figure out how we display computer software and I added an issue #239 to create the software request form.  @cappadona is already working showing laptop availability so I think we're in good shape.

**Comment by cappadona** [comment]
Thanks @sew268...two things.

1. I have #139 assigned to me for wiring up computer availability, but it's currently in the icebox so I'm not working on it now and don't plan to be during this sprint.

1. Speaking of the icebox, this issue is there as well...should it be?

**Comment by sew268** [comment]
@cappadona  - sounds great about #139 - room availability is top billing this round but I'm glad there's an issue out there to tackle computer availability.  The 'this issue' you refer to is #239?  If so, then yes I think that stays in the ice box; should be easy-ish to do after then forms are done for 100/102.  If 'this issue' is the software availability - I still need to create an issue for that and I think for now, it can go in the icebox but maybe I can start thinking about how it could be laid out?

**Comment by sew268** [comment]
@cappadona ...and I just realized what you meant by 'this issue' :)  Been a long day and I'm on a lot of allergy medicine.  
I'll move #138 to baked

**Comment by cappadona** [comment]
No worries and thanks. Pollen index has been through the roof here the past couple days after the week of rain giving everything green a solid boost. Hang in there.
