### ISSUE TITLE
Key information for find a space

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#143]
> See screenshot of prototype in #142

**Comment by eeh53** [comment]
### Study Spaces
**Bissett Collaborative Workstations**
- 4 semi-private booths, can accommodate up to 5 people
- built-in computer and LCD
- VGA and HDMI connectors for laptops
- 2 workstations are reservable up to one week in advance for 2 hours at a time

**Interview Room**
- BYOD private room for web-based video conferencing, can accommodate up to 4 people
- table and 4 chairs
- large LCD screen 
- webcam and microphone
- reservations may be made up to one week in advance for 2 hours at a time

**One Button Studio**
- stand-alone camera, microphone, and LCD preview monitor to record speeches and presentations 
- wall-mounted LCD 
- table and 4 chairs
- reservations may be made up to one week in advance for 2 hours at a time

**The Hive (Room 282)**
- large group study room, can accommodate up to 7 people
- large screen LCD and HDMI connection
- large table that seats 7
- reservable after 6:00 pm until closing, Monday - Friday,  and all day Saturday and Sunday
- reservations may be made up to one week in advance for 2 hours at a time


### Classrooms
**Stone Computer Classroom**
- 26 Dell computers and 1 instructor station
- webcam and microphone for distance learning and lecture capture
- may be reserved for instructional use by Cornell faculty and teaching staff, with preference given to Mann Library staff up to one semester in advance
- intended for non-recurring or limited recurring instruction

**B30A Computer Classroom**
- 43 Dell computers and 1 instructor station
- webcam and microphone for distance learning and lecture capture
- may be reserved for instructional use by Cornell faculty and teaching staff via [CALS Registrar's office](cals-rooms@cornell.edu) up to one semester in advance
- intended for recurring and one-time instruction

**B30B Computer Classroom**
- 30 Dell computers and 1 instructor station
- webcam and microphone for distance learning and lecture capture
- may be reserved for instructional use by Cornell faculty and teaching staff via [CALS Registrar's office](cals-rooms@cornell.edu) up to one semester in advance
- intended for recurring and one-time instruction

**CIT Computer Classroom**
- 25 Dell computers and 1 instructor station
- 3 Net Print printers (two black & white, one color)
- may be reserved for instructional use by Cornell faculty and teaching staff via [CIT](http://labs.cit.cornell.edu/request-a-lab/)

**CIT MacLab Classroom**
- 21 iMac computers and 1 instructor station
- 3 Net Print printers (two black & white, one color)
- may be reserved for instructional use by Cornell faculty and teaching staff via [CIT](http://labs.cit.cornell.edu/request-a-lab/)


### Seminar & Conference Rooms
**Conference Room 102**
- large conference room seats up to 50 people
- videoconferencing unit (Cisco VTC) and web-based video conferencing (WebEx and Skype)
- podium microphone, ceiling microphones, and lavaliere microphone
- presenter podium with Dell computer
- intended for non-recurring or limited recurring events

**Seminar Room 100**
- small seminar room seats up to 17 people
- BYOD web-based videoconferencing (WebEx and Skype)
- large LCD monitor
- webcam and microphone
- presenter podium with Dell computer
- intended for non-recurring or limited recurring events

**Comment by eeh53** [comment]
I've taken a first stab at what might be considered the key information about these spaces, but @sew268 might want to take a look at this to see if she agrees. I also consulted Matt Ryan and he and I had very similar answers, which is promising.

**Comment by cappadona** [comment]
Thanks @eeh53. This is great. A couple initial comments & questions:

1. I'm basically seeing this info loosely fall into the following categories...
  1. capacity
  1. quantity
  1. description
  1. equipment
  1. furniture
  1. reservable?
  1. intent and/or purpose

1. Can we consolidate any of these? Maybe equipment/furniture and description/intent?

  > Said another way, do you think we could shoe-horn them into the limited fields provided by LibCal? `name`, `capacity`, `description`, `directions`, `image_url`

1. Are any of these categories higher priority than the others?

  > There's a lot here so if we decide to only render a subset/overview at first, what should be included?

1. What about the study rooms (`indiv`, `group`, `grad`) available for loan at Circ?

**Comment by eeh53** [comment]
Thanks for looking this over, @cappadona! Sara and I still need to go over it and see if anything can be condensed.I think the categories you've described accurate, and I also think some of the info included could be shared in a different way, e.g. if the space is reservable, then just have a link to "reserve this space" which will have more information about who can reserve the space, how far in advance, etc. 

You're absolutely right that I forgot to add the individual, group, and grad study rooms, so I will add those now. Also, I realized I forgot to include the lobby, so I'm going to add that as well.

**Comment by eeh53** [comment]
@cappadona We really like what we're seeing at OU http://library.uoregon.edu/rooms-study-spaces

**Comment by cappadona** [comment]
[Here's a sketch](https://github.com/cul-it/mann-wagon/issues/12#issuecomment-183361777) from our early thinking on this topic.
