### ISSUE TITLE
Report `currently_open` bug to LibCal support (Hours API)

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#152]
I tried both of the following for yesterday's hours:

* add an exception with earlier closing

* change the LibCal template to use an earlier closing for Mondays

After the new closing times had passed, the LibCal API still returned: `currently_open` = `true`

Discovered as part of #133.

**Comment by tap87** [comment]
Apparently the api responses are cached for 1 hours. I will modify the api call to return live values.

Here is the response from SpringShare:
We cache the Hours widgets for 1 hour, so you could be seeing old values when refreshing/updating the templates? 

To bypass the cache and get live values, you can append &nocache=1 to the request URL:
https://api3.libcal.com/api_hours_today.php?iid=973&lid=1707&format=json&nocache=1

**Comment by cappadona** [comment]
Thanks, Tahir. Good to know. Undocumented feature?

**Comment by tap87** [comment]
Most likely, I didn't read about this in the help documents.

**Comment by cappadona** [comment]
Yeah, I also don't remember coming across it but it seems like an important detail, especially when current opening status is in question ;)

**Comment by tap87** [comment]
Thought I had seen this somewhere, finally found it. It is on the widgets section under hours in libcal, but I agree, documentation should exist for this. I will email SpringShare about it.

Note: Widget requests will be cached to conserve processing. The cache is cleared every 1 hour.

**Comment by cappadona** [comment]
Thanks...I think that note may be new, as is the `JSON-LD` option. Most importantly, I was under the impression that the API is distinct from the widgets.

I appreciate you getting to the bottom of this and passing on our feedback to SpringShare.
