### ISSUE TITLE
Cannot upload files into Assets in Locomotive

### ISSUE THREAD

**Issue by eeh53** [cul-it/mann-wagon#162]
I tried uploading some images of the library into the Assets section in Locomotive, but they won't upload. @cappadona tried to recreate the issue and was able to upload a screenshot successfully. We think it might be a size limit issue, but aren't sure. Adding this as a bug so we don't lose track of it.

**Comment by cappadona** [comment]
@eeh53 @sew268 All set. This was an Nginx configuration. I bumped up the `client_max_body_size` to 5MB. Easy fix thanks to [cyberciti article](http://www.cyberciti.biz/faq/linux-unix-bsd-nginx-413-request-entity-too-large).

cul-it/mann-locomotive@450125c

**Comment by cappadona** [comment]
P.S. I recommend using the Assets manager to upload files instead of uploading a local file directly while editing a content type.
