### ISSUE TITLE
Booked API for reservations doesn't return custom attributes, to specify reservation type, etc.

### ISSUE THREAD

**Issue by tap87** [cul-it/mann-wagon#163]
Booked doesn't have a default reservation type field. We could use custom fields for that, but the [api for getting reservations](http://booked-dev.library.cornell.edu/Web/Services/index.php#Reservations) doesn't return these. We need to pass custom attributes in this method in order for filtering to work properly.

**Comment by tap87** [comment]
I have submitted a feature request to booked developers for this issue.

**Comment by cappadona** [comment]
Thanks. Have a link?

**Comment by tap87** [comment]
Yes, I have updated my comment.

**Comment by cappadona** [comment]
Thank you...looks like there are 182 feature requests for the next release, with 70 of them already closed. Any idea how they decide what to prioritize?

**Comment by tap87** [comment]
I am not sure. I see a voting option, but that doesn't seem to be a factor as most of the issues have 0 votes.

**Comment by cappadona** [comment]
I hear ya...I guess we'll see what happens :)

**Comment by tap87** [comment]
See #164 Baking this one.

**Comment by cappadona** [comment]
@tap87 I'm confused. #164 is already closed, and references this issue for our decision to go with custom attributes. Did you mean to reference #233?

**Comment by tap87** [comment]
@cappadona Thank for catching that, I have fixed it now.
