### ISSUE TITLE
Allow multiple parameters in Booked API reservations method

### ISSUE THREAD

**Issue by tap87** [cul-it/mann-wagon#164]
[Booked API for reservations](http://booked-dev.library.cornell.edu/Web/Services/index.php#Reservations) allows resourceID (room) parameter, but takes a string value, so we are limited to one room only. As a workaround for #163, we are tying reservation type to a room (e.g., stone room for workshops only), we want to be able to pass multiple resourceID's to avoid making separate call for each room. Otherwise, we will have to combine data from each room separately with the localist data.

**Comment by cappadona** [comment]
If we update the API to return reservation type, we won't need this. See #163

**Comment by cappadona** [comment]
Going with custom attributes in #163
