### ISSUE TITLE
Modify reservation forms so that they are more tailored to each room and the number of questions is reduced

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#17]
https://issues.library.cornell.edu/browse/MANNWEB-136

**Comment by eeh53** [comment]
[Info for Reservation Forms (1).docx](https://github.com/cul-it/mann-wagon/files/123683/Info.for.Reservation.Forms.1.docx)

**Comment by eeh53** [comment]
Sara and I worked on what information we would want to capture on reservation forms for the seminar and conference rooms, the lobby, Stone classroom, Bissett/One Button Studio/Interview Room/Group Room(s), and the Gallery. See attachment.

**Comment by sew268** [comment]
Tobi created new issues for each of the reservations forms #74 #75 #76 #77 #78.
