### ISSUE TITLE
Filter and/or search for events 

### ISSUE THREAD

**Issue by dbranchini** [cul-it/mann-wagon#178]
We need to discuss this requirement and further define it.  We might also discover what is required/needed during the first round of usability testing.

**Comment by cappadona** [comment]
I stumbled across [list.js](http://www.listjs.com) a couple weeks back. Might be useful if it turns out Vue needs assistance with something like this.

**Comment by tap87** [comment]
Filtering events by all fields for now, we can specify which fields to include.

**Comment by tap87** [comment]
We need to discuss search in more detail if we want users to search for events. It gets complicated since booked doesn't have a search function. We could pin our hopes on search engines indexing events, but not sure how well that is going to work.

**Comment by cappadona** [comment]
Agreed...will you create an issue for including events in site-search if you haven't already, so we don't lose track of this?

**Comment by tap87** [comment]
Created a new issue for site search to include events, see #213

**Comment by cappadona** [comment]
Thanks!
