### ISSUE TITLE
Links on home page 

### ISSUE THREAD

**Issue by dbranchini** [cul-it/mann-wagon#184]

**Comment by dbranchini** [comment]
- [] all events link
- [] all workshops & classes (change to this title too)

**Comment by eeh53** [comment]
So looking into this a little more, we found the recommendation from the Research Enhancements team, which is below:

**1. Link to major subject guides from the front page**
The Purdue University Library website is an example of this.  The Mann Library website once had a list hidden under the side menu "research help" > "guides by subject", but it broke during the 2014 LibGuides upgrade.  However, it should still be possible to automatically generate a list of selected guides using the current LibGuides API.  We would not necessarily highlight every guide created by Mann staff, but rather a set of approximately 5 to 10 broader subject guides, which would be included by virtue of being assigned a specific tag (such as "mann-top") within LibGuides.  This tagging would need to be coordinated with Mann subject guide authors, and these top-level guides would require time from each author to adequately cover the subject area in a consistent manner.  However, we believe that the data generated from our user interviews justifies the time and effort required.  The final configuration of top-level guides would need to be worked out among the subject librarians, but the list would look something like this:

- Agricultural Economics & Business

- Food Systems & Agriculture

- Health Science & Policy

- Environmental Sciences

- Applied Social Sciences

- Life & Biological Sciences

- Environmental & Fiber Design

**Comment by eeh53** [comment]
For the purposes of usability testing, here are the links for the search results of these areas across all CUL LibGuides:

- Agricultural Economics & Business: http://guides.library.cornell.edu/srch.php?q=agriculture+economics+and+business&t=0
- Food Systems & Agriculture: http://guides.library.cornell.edu/srch.php?q=agriculture+economics+and+business&t=
- Health Science & Policy: http://guides.library.cornell.edu/srch.php?q=health+science+and+policy&t=0
- Environmental Sciences: http://guides.library.cornell.edu/srch.php?q=environmental+sciences&t=0
- Applied Social Sciences: http://guides.library.cornell.edu/srch.php?q=applied+social+science&guide_id=154284
- Life & Biological Sciences: http://guides.library.cornell.edu/srch.php?q=life+and+biological+sciences&t=0
- Environmental & Fiber Design: http://guides.library.cornell.edu/srch.php?q=environmental+and+fiber+design&t=0
