### ISSUE TITLE
Make Find a Space more scannable

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#199]
Start by decreasing text on cards, using icons and calling attention to:

* capacity
* reservable/loanable
* current availability
* ~~who can use it (primarily grad vs. undergrad)~~ #227 
  * also certain spaces not available to faculty

Later add...

* ~~filters~~ #267
* ~~grid/matrix view~~ #268

**Comment by sew268** [comment]
For inspiration: http://library.unc.edu/places/study/

**Comment by cappadona** [comment]
First go at this deployed to dev. Covers all of the initial items in the first comment on this issue, aside from **who can use it**.

More details of changes made and TODO in 1f86556.

**Comment by cappadona** [comment]
who can use it now covered by #227
