### ISSUE TITLE
Add details to home page regarding computer and room availability, consultation services, lidguides and tutorials, and current workshops

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#20]
https://issues.library.cornell.edu/browse/MANNWEB-139

**Comment by cappadona** [comment]
Refined the information under available now section of home page as part of [MANNWEB-168](https://issues.library.cornell.edu/browse/MANNWEB-168).

> Jira comment from 2015-02-19

**Comment by eeh53** [comment]
Most of this is covered by current homepage design. Homepage is being redesigned, so closing this issue.
