### ISSUE TITLE
URL addressable events

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#209]
So we can link directly to filtered views (e.g. Workshops & Classes from the home page) and single events.

**Comment by tap87** [comment]
event: {
id: 652884,
title: "Vintage Vision: Vogel, Vogue and the Art of "Gazette Du Bon Ton"",
url: "http://mannlib.cornell.edu/events-exhibits",
updated_at: "2016-06-09T06:54:49-04:00",
created_at: "2016-04-08T09:53:44-04:00",
facebook_id: null,
first_date: "2016-04-08",
last_date: "2016-08-31",
hashtag: "",
urlname: "vintage_vogue",
user_id: 8954,
directions: "",
allows_reviews: true,
allows_attendance: true,
location: "Mann Library",
room_number: "Lobby",
location_name: "Mann Library",
created_by: 8954,
updated_by: 8954,
city_id: null,
neighborhood_id: null,
school_id: 10,
campus_id: null,
recurring: true,
free: true,
private: false,
verified: true,
rejected: false,
sponsored: false,
venue_id: null,
ticket_url: "",
ticket_cost: "Free and open to the public",
keywords: [
"exhibit",
"illustration",
"History",
"fashion",
"Cornell University Library",
"Mann Library",
"apparel design"
],
tags: [
"illustration",
"exhibit",
"history",
"Cornell University Library",
"Mann Library",
"fashion",
"apparel design"
],
description_text: "In 1912 Lucien Vogel started a new magazine dedicated to presenting the fashions of the most prominent Parisian design houses in the most luxurious way possible - la Gazette du Bon Ton. By 1923 he was the Art Director of Condé Nast's VOGUE Paris. In between, a stable of brilliant young artists filled the pages of Gazette du Bon Ton with stylish pochoir prints which would help propel Art Deco to the forefront of the design world. Together, these publishers, painters, and craftsmen would shape the art of fashion for decades to come. “Vintage Vision” spotlights a selection of images from the Gazette, reproduced from Mann Library's special collections to highlight the brilliance and impact of this artistry. Also featured are vintage clothing loaned by the Cornell Costume and Textile Collection in the College of Human Ecology, as well as work by current students of FSAD 2640 (Fiber Science and Apparel Design – Draping), who, under the guidance of professor Susan Ashdown, have transformed some of the exhibit’s silhouette images into exquisite half-size models of flowing, textured fabric.",
photo_id: 375710,
detail_views: 1004,
address: "",
description: "<p>In 1912 Lucien Vogel started a new magazine dedicated to presenting the fashions of the most prominent Parisian design houses in the most luxurious way possible - la <i>Gazette du Bon Ton</i>. By 1923 he was the Art Director of Cond&eacute; Nast&#39;s VOGUE Paris. In between, a stable of brilliant young artists filled the pages of <i>Gazette du Bon Ton</i> with stylish pochoir prints which would help propel Art Deco to the forefront of the design world. Together, these publishers, painters, and craftsmen would shape the art of fashion for decades to come.</p> <p>&ldquo;Vintage Vision&rdquo; spotlights a selection of images from the <i>Gazette</i>, reproduced from Mann Library&#39;s special collections to highlight the brilliance and impact of this artistry. Also featured are vintage clothing loaned by the Cornell Costume and Textile Collection in the College of Human Ecology, as well as work by current students of FSAD 2640 (Fiber Science and Apparel Design &ndash; Draping), who, under the guidance of professor Susan Ashdown, have transformed some of the exhibit&rsquo;s silhouette images into exquisite half-size models of flowing, textured fabric. &nbsp;</p> ",
featured: false,
geo: {
latitude: null,
longitude: null,
street: null,
city: null,
state: null,
country: null,
zip: null
},
filters: {
departments: [
{
name: "Cornell University Library",
id: 4205
},
{
name: "Mann Library",
id: 4228
},
{
name: "Fiber Science & Apparel Design",
id: 4952
}
],
event_types: [
{
name: "Exhibit",
id: 4257
}
]
},
custom_fields: {
contact_email: "ker87@cornell.edu",
contact_name: "Karl Rozyn",
open_to: "Public"
},
localist_url: "http://events.cornell.edu/event/vintage_vogue",
photo_url: "http://images-cf.localist.com/photos/375710/huge/2816e1d62b5c4ec324bb3487974af34bb325f0c0.jpg",
venue_url: null,
event_instances: []

**Comment by cappadona** [comment]
thanks for the update @tap87. Will you let us know when the latest is deployed to dev so we can take it for a spin?

**Comment by tap87** [comment]
![image](https://cloud.githubusercontent.com/assets/4334244/16119671/7f58f4a4-33aa-11e6-8d41-6580a327ec66.png)

**Comment by tap87** [comment]
Moving to icebox, till we decide on reservation system.

**Comment by cappadona** [comment]
Booked is out. LibCal is in.

**Comment by cappadona** [comment]
@tap87 Not worth our time in my opinion. Scrapinghub is a temporary site search solution. So if this is the only way to implement vue.js routes then we're going to have to ensure our real site search solution can harvest and index these URLs. Let me know if you disagree.

**Comment by tap87** [comment]
@cappadona Ok, sounds good to me.

**Comment by tap87** [comment]
There is still an issue with using url's for events/event types etc. If we want the search to show up any events, then we will have to use links, which breaks the concept of single page application.Whenever we use a link for the events, it causes a page reload. In our last meeting on this topic, we decided to avoid links on event types, rooms, calendar, etc on the events page and only voted for links from the homepage to the events page for certain event types (classes/workshops).
