### ISSUE TITLE
Embed LibCal Reservation Widget

### ISSUE THREAD

**Issue by eeh53** [cul-it/mann-wagon#220]

**Comment by tap87** [comment]
@eeh53 @sew268 Nick and I discussed the option of embedding the [widget](http://spaces.library.cornell.edu/room_wsetup.php) vs the [public facing reservation page](http://spaces.library.cornell.edu/booking/interview). The user experience is somewhat different in both these options. Would you guys mind checking both these options out and see which experience you prefer.
For the widget link, Select the room, 
![screen shot 2016-05-06 at 9 43 02 am](https://cloud.githubusercontent.com/assets/4334244/15074833/37162e1a-136f-11e6-93be-c093deddafea.png)
click the generate code and then preview the widget in the link I provided.

**Comment by sew268** [comment]
Sorry for the delay - we both just had a chance to do this and we both prefer the widget experience but we also wondered if it would be possible to instead of having a list of dates to select from, have a clickable calendar to select your date??  I'm guessing the answer is "yes, but..." :)

**Comment by cappadona** [comment]
Thanks for the feedback. Actually, this one is simple...unfortunately the answer to your question is **No**.  :(

We have zero control over the widget. What you see is what you get. You want to change your preference or can we move forward with implementing the widget for LibCal reservations?

**Comment by cappadona** [comment]
Going to stick with widget and submit [feature request to SpringShare](http://ask.springshare.com/ask)

**Comment by tap87** [comment]
@cappadona I just pushed a [branch](https://github.com/cul-it/mann-wagon/tree/libcal-reservations) with the widget. Let me know what you think.

**Comment by tap87** [comment]
Deployed to dev.
