### ISSUE TITLE
Show Loanable Study Room Accessibility Information

### ISSUE THREAD

**Issue by eeh53** [cul-it/mann-wagon#221]

**Comment by cappadona** [comment]
Updated title to make this explicit to accessibility information since availability is already covered by #224, #225, #226

**Comment by cappadona** [comment]
* Claim?
* Access?
* **Borrow?**
* **Loan?**
* Checkout?

Borrow is the big winner

**Comment by cappadona** [comment]
Just deployed some changes to dev. @sew268 & @eeh53, what would you like to happen when someone clicks the **borrow** button for loanable rooms?

**Comment by cappadona** [comment]
P.S. Noticed a difference between serving the site via wagon and engine, which is causing the dev site to show all non-reservable spaces as loanable at the moment. More to come...

**Comment by sew268** [comment]
@cappadona @eeh53 maybe the borrow button could link to the smartmap with the circ desk highlighted?  Either that or the contact info for the circ desk.

**Comment by cappadona** [comment]
During today's discussion we decided to:

* drop the button
* keep the key
* change the language to *Check out the key at the circulation desk for a X-hour loan* (or something along those lines)

**Comment by cappadona** [comment]
Deployed to dev.
