### ISSUE TITLE
Layout and configure individual space template

### ISSUE THREAD

**Issue by eeh53** [cul-it/mann-wagon#227]

**Comment by cappadona** [comment]
### Carried over from #199

> who can use it (primarily grad vs. undergrad)
also certain spaces not available to faculty

From 5/13/16 discussion, main focus is using alert on this view to indicate that loanable study rooms are not for faculty use

**Comment by cappadona** [comment]
Deployed to dev. As mentioned in message for d052502, this is far from done. We should create new issues for specific improvements we want to make.
