### ISSUE TITLE
Add button to book a GIS consultation linked to LibCal My Scheduler

### ISSUE THREAD

**Issue by eeh53** [cul-it/mann-wagon#231]

**Comment by tap87** [comment]
@cappadona Is there a placeholder on the page for the my scheduler button.

**Comment by cappadona** [comment]
@tap87 Nope. I believe @eeh53 & @sew268 envisioned the button sitting adjacent to the last sentence in the first paragraph:

> If the walk-in hours are not convenient for you, please request a one-on-one consultation to fit your schedule. 

There's no easy way of doing this at the moment, aside from hardcoding something in the `wysihtml` markup view. This should be a much better experience once [this feature is implemented](https://trello.com/c/qnnObbhJ) as part of the core. For now we might be best committing the template for the GIS page into the repo and building the link in the template.
