### ISSUE TITLE
Organize categories for hours pages

### ISSUE THREAD

**Issue by eeh53** [cul-it/mann-wagon#232]

**Comment by sew268** [comment]
**Top Category (Building):**
Mann Library
Lobby
Manndible
Basement

**Next Category (Service Desks):**
Circulation
Info & Research Help Desk
Poster Printing

**Next Category (Consultation Services):**
GIS Help Desk
RDMSG
CISER Help Desk
CSCU Help Desk
Knight Writing Walk in Service
ELSO

**Comment by cappadona** [comment]
@sara Nice. Quick question. Are we planning on adding a **Circulation** dept. in LibCal or are you hoping to just repeat **Mann Library** hours here?

**Comment by sew268** [comment]
We were thinking we'd create a new department and then apply the Mann Library template to circulation.

**Comment by sew268** [comment]
@tap87 reassigned to you since categories are done :)

**Comment by cappadona** [comment]
@sew268 That sounds good. Thanks for clarifying :)

**Comment by tap87** [comment]
@sara. Thanks.

**Comment by tap87** [comment]
@eeh53 I saw that you changed the names of CISER, CSCU Help Desks, and also created special collections department in Libcal. Do you want to update the comment above with the categories.

**Comment by eeh53** [comment]
@tap87 I've updated the names of the departments/desks above to match what's in LibCal, and added the Special Collections dept. to the "service desks" category.

**Comment by tap87** [comment]
@eeh53 Great. Thanks.

**Comment by tap87** [comment]
I have updated the names and categories, see [commit](https://github.com/cul-it/mann_liquid_extensions/commit/2cacde31e89bbed2fe48eb6ef9d456db3b74dc29).

**Comment by cappadona** [comment]
Thanks, @tap87. Latest locomotive deployed to dev.
