### ISSUE TITLE
Allow custom attributes in the response for reservations in Booked API

### ISSUE THREAD

**Issue by tap87** [cul-it/mann-wagon#233]
See #163. Since we have no idea on the timeline this features will be implemented, we will have to modify the API and return the custom attributes.

**Comment by tap87** [comment]
I am working on installing a local instance of booked (v 2.6)

**Comment by tap87** [comment]
Finally got the local instance running, had to fix some errors to get it working.

**Comment by tap87** [comment]
We now have custom attributes in the response for getting reservations, see https://github.com/cul-it/mann-booked/commit/3306a4c6ee1fcf0e5dd7c89bc72dc98b230c06ea

**Comment by cappadona** [comment]
@tap87 Just tested and this looks great! Thanks.

**Comment by tap87** [comment]
@cappadona Thanks for testing this, now I have your word as well.
