### ISSUE TITLE
Implement webpack vue-loader

### ISSUE THREAD

**Issue by tap87** [cul-it/mann-wagon#235]

**Comment by tap87** [comment]
@cappadona See the[ vue-loader branch](https://github.com/cul-it/mann-wagon/tree/vue-loader) for details.

**Comment by cappadona** [comment]
@tap87 Finally got a chance to review this. Was able to `npm install` and `npm run build` without a hitch and everything seems to be working :)

I have a couple questions that I'll send your way. Thanks!
