### ISSUE TITLE
Identify fields for staff content types to power experts

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#236]
Building off of #197

**Comment by sew268** [comment]
(Fields would appear only if they are populated)

Name:
**link under the name for contact info which takes you to staff directory for email, phone, & office location information**
Title:
Photo:
**link under photo for video if applicable.  Button might say 'Learn more about Tom' for examp**le. 
Liaison to:
Areas of Expertise:
Book a consultation link:
**all 3 fields would be to the right of the photo**

http://www.english.upenn.edu/ - scrolling down to 'meet the faculty' is good inspiration for highlighting librarians on the homepage.  We love the circular photos which they carry through to the faculty directory page.

**Comment by sew268** [comment]
@cappadona  - let us know if you want to have a quick phone call to help explain this a bit :)

**Comment by cappadona** [comment]
@sew268 @eeh53 I think I'm picking up what you're laying down. I've just edited the formatting of your comment to convey how I understood it.

And what your describing is specific for the GIS sampler we're planning on building this time around or can be more broadly applied?

**Comment by sew268** [comment]
Ok here's a draft of what we were thinking for rotating librarian images on the homepage, then the page that lists experts, and then the staff directory.
[Directories.pdf](https://github.com/cul-it/mann-wagon/files/259877/Directories.pdf)

**Comment by cappadona** [comment]
@sew268 @eeh53 Nice timing. I just deployed an **academic departments** `content type` along with 3 others (see #197), which should help us make this a reality.

Feel free to start populating them with data :)
