### ISSUE TITLE
Create template for expertise @Mann page

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#237]
see pdf in #236 

Link to it from the home page via **Meet All Our Experts** (part of meet-librarians)

Triggered by a populated **expertise** field in the staff content type

Should provide filtered view for **Find your Librarian** as well

> Be sure to include `staff-book-consultation` snippet #560

**Comment by eeh53** [comment]
Start populating expertise field in staff content type

**Comment by cappadona** [comment]
Hi everyone. This is finally deployed to dev. I'm currently cleaning up duplicate academic departments in the back office.

**Comment by cappadona** [comment]
Okay...duplicate depts have been snuffed out.

@sew268 & @eeh53: There are several academic departments that have no liaison identified and the site doesn't handle this very gracefully at the moment.
