### ISSUE TITLE
Priority Area 7: Create forms

### ISSUE THREAD

**Issue by sew268** [cul-it/mann-wagon#239]
- ~~software request form~~ #298 
- ~~special collections request form~~ #299 
- ~~instruction request form~~ #300 
- ~~consultation request form~~ #301 
- ~~request a purchase form~~ #311

**Comment by sew268** [comment]
- [ ] software request form
- [ ] special collections request form

**Comment by cappadona** [comment]
@sew268 I see what you did here, and I like it. Just moved your running list into the first comment body so GitHub will automatically track progress.

**Comment by eeh53** [comment]
@sew268 @cappadona Would room reservation forms not be included in this list, since that's something we have to do via LibCal (with the widget) and Booked?

**Comment by cappadona** [comment]
As @eeh53 and I've been discussing just now via chat, we're leaning towards 2 epics:

1. Room reservation forms
1. All other forms

**Comment by eeh53** [comment]
Thanks, @cappadona. I convert this issue to a PA epic and break out the list above into separate tasks.

**Comment by sew268** [comment]
@cappadona @eeh53 Those 2 epics sound good to me!

**Comment by cappadona** [comment]
Need to decide whether we'll use content types for simple forms like these
