### ISSUE TITLE
Gracefully degrade when events data sources are down

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#249]
Thought of this when I noticed the home page and events continuously display **loading...** while you have Booked offline during the upgrade.

Change the message to say `Events currently unavailable. Report this issue.` <-- link to Site feedback form

Something to address down the road before we go live...

**Comment by cappadona** [comment]
If all data sources are down and we have no events to render, then display a message to the user in the website. Otherwise, log the errors so that we're aware of it.

Contact Alan about log notification.

**Comment by tap87** [comment]
Deployed to dev
