### ISSUE TITLE
Render room availability from LibCal

### ISSUE THREAD

**Issue by eeh53** [cul-it/mann-wagon#255]

**Comment by cappadona** [comment]
For each of these tasks related to room availability, here's what I had in mind:

* available now?

* if not, when is it next available?

**Comment by tap87** [comment]
@cappadona How and where are we displaying "next available"?

**Comment by cappadona** [comment]
Depends on the context. Here's some of the ideas I've had:

* home page: display next available via tooltip/popup (if we revamp the home page, then perhaps we won't need to hide this additional info by default)

* find a space: next available details will render in the meat of the card, where the reserve button sits

Bottom line, don't sweat the details on how the data will be displayed, these issues are more about delivering the data to the templates.

Let me know if you have any additional questions?

**Comment by tap87** [comment]
Thanks @cappadona. For the next available, do we check dates in the future as well, if no time slots are available today?

**Comment by cappadona** [comment]
@tap87 Yeah, that would be ideal. No worries if we leave that as an enhancement to implement later.

**Comment by tap87** [comment]
@cappadona Thanks. Just out of curiosity, is it possible to pass a date parameter for the mannservices api to get future availability.

**Comment by cappadona** [comment]
@tap87 Yep, parameter is `date` and format is `YYYY-MM-DD`
