### ISSUE TITLE
Render room availability from Booked

### ISSUE THREAD

**Issue by eeh53** [cul-it/mann-wagon#256]

**Comment by cappadona** [comment]
For each of these tasks related to room availability, here's what I had in mind:

* available now?

* if not, when is it next available?

**Comment by tap87** [comment]
@cappadona This one is complicated because booked api calls need authentication. Consume tag won't help here.

**Comment by cappadona** [comment]
@tap87 Good point. We should be able to use `consume` for the initial call, assign the sessionToken to a Liquid variable and then use that for a followup call via `consume`, but this all hinges on being able to send a `POST` request via consume and I'm not sure that's possible.

**Comment by cappadona** [comment]
Deployed to dev in time for usability testing round 2
