### ISSUE TITLE
make navigation more prominent, change location on page

### ISSUE THREAD

**Issue by dbranchini** [cul-it/mann-wagon#257]

**Comment by cappadona** [comment]
Deployed to dev. Let me know if you think this is good to go for upcoming testing.

**Comment by sew268** [comment]
The hours page is looking really good!  My only suggestion would be to center the navigation arrows over the week but we can also leave it where it is and see if anyone comments during usability testing.

**Comment by cappadona** [comment]
A quick survey shows the conventions for calendar nav are upper left or right. I just deployed a change that pushes the nav to the upper right. The bonus is that it bumps the hours table further up the page :)

Let me know which you prefer.

<img width="1047" alt="screenshot 2016-05-16 13 59 50" src="https://cloud.githubusercontent.com/assets/409842/15298985/4f70c1c4-1b70-11e6-8f99-8ca42dd413ae.png">

<img width="1295" alt="screenshot 2016-05-16 14 01 17" src="https://cloud.githubusercontent.com/assets/409842/15298995/5a2c5aec-1b70-11e6-98b7-77071d7814b4.png">

<img width="1295" alt="screenshot 2016-05-16 14 05 40" src="https://cloud.githubusercontent.com/assets/409842/15299008/6509d5e8-1b70-11e6-8c21-31a632347cfb.png">

<img width="1092" alt="screenshot 2016-05-16 14 07 11" src="https://cloud.githubusercontent.com/assets/409842/15299014/6c913824-1b70-11e6-90be-03756f88c9fa.png">

**Comment by sew268** [comment]
silly conventions :)  I think I like it in the upper right better!

**Comment by cappadona** [comment]
Thanks. I do as well...let's roll with this for now :)
