### ISSUE TITLE
change styling for location names

### ISSUE THREAD

**Issue by dbranchini** [cul-it/mann-wagon#260]

**Comment by cappadona** [comment]
Deployed to dev. Didn't make the 3 non-linked locations look identical to the linked ones. Thought that would be confusing to the user. Are we thinking we'll never have links for any of these?

1. Mann Library
1. Basement
1. Circulation

I thought **Mann Library** might be the lone exception...

**Comment by sew268** [comment]
Basement and Circulation we'd never have links for - Mann Library could be...I'm fine either way.

**Comment by cappadona** [comment]
@sew268 I was thinking we would have a link for the basement re: **floorplans**. Also, the staff directory content type introduces service desks, and with that we should at least have a phone number for each, so is it too much of a reach to think we could link to the contact info for circ?

What did you have in mind for Mann Library link?

**Comment by sew268** [comment]
@cappadona oh interesting...I like both ideas: linking to the floor plan and the service desk info.  The only thing that came to mind for Mann Library was a link to the homepage much like clicking on the Mann Library in the top left takes you back to the homepage.  Although as I type this, it could go to the 'About us' page...maybe that's too much of a stretch :)

**Comment by cappadona** [comment]
@sew268 Haha...I like where you're headed. I think these are 3 good options for the **Mann Library** link:

* about us
* contact us
* organization & staff (aka staff directory)

**Comment by sew268** [comment]
@cappadona Of the 3 I would lean towards 'about us' but they are all good if others feels strongly that it should be one of the other two

**Comment by cappadona** [comment]
@sew268 Sounds good. Should we create a new issue for @eeh53 to fill in the blanks from the LibCal side?

**Comment by sew268** [comment]
@cappadona I just added links and I'm about to send you a question in hipchat
