### ISSUE TITLE
Add field in staff content type to designate some as 'not Mann staff'

### ISSUE THREAD

**Issue by sew268** [cul-it/mann-wagon#262]

**Comment by cappadona** [comment]
Deployed to dev. @eeh53 @sew268, feel free to add Jeremy :)

**Comment by sew268** [comment]
Added Jeremy to the Staff Directory.  Tobi and I have discussed this and - as a liaison - Jeremy should appear on the Experts Page but he should not be included in the rotating list of photos on the homepage.  This means we'll probably need to use the 'not Mann staff' as a filter, in addition to the librarian field and epxerts fields, for what is pulled for that feature.

**Comment by cappadona** [comment]
Thanks @sew268 @eeh53. I was thinking we could just filter out Jeremy from the home page by not identifying him as a librarian. The Liaison page can filter on any staff who are associated with a department via the `liaison` field and would not make use of the `librarian` field. That work?

**Comment by sew268** [comment]
Perfect...look at me always making it more complicated than it has to be :)
