### ISSUE TITLE
Reuseable content - Hours

### ISSUE THREAD

**Issue by eeh53** [cul-it/mann-wagon#264]
* ~~Consultation Services~~ #328 
* ~~Poster Printing~~ #329
* ~~Spaces - general and individual~~ #330 & #331
* ~~Special Collections - special collections page and request/registration form~~ #332 & #333

**Comment by tap87** [comment]
I have created separate issues for each item in the list, and am closing this one.

**Comment by cappadona** [comment]
Thanks Tahir! If anything new comes up for hours related reusable content, we should just add a new issue directly.
