### ISSUE TITLE
Set up content type for news

### ISSUE THREAD

**Issue by eeh53** [cul-it/mann-wagon#294]

**Comment by cappadona** [comment]
Meeting with Eveline tomorrow to discuss this.

**Comment by cappadona** [comment]
> Notes from meeting with Eveline

* keep fields from [existing Drupal form](http://mannlib.cornell.edu/node/add/news)
  * title
  * published date
  * body
  * tags
  * image
  * image alignment
* perhaps drop the tags -- Eveline is going to check with Outreach group
* don't automatically use last X on home page
  - manually curate featured via boolean field (include in spotlights on home page?)

**Comment by cappadona** [comment]
Deployed to dev.
