### ISSUE TITLE
Configure Booked so that it is fully operational

### ISSUE THREAD

**Issue by sew268** [cul-it/mann-wagon#303]

**Comment by cappadona** [comment]
@tobi @sew268 We're going to need more details on what this means. We can start with a running list here if it's easier, but most likely we'll want to convert this to an epic and create sub-tasks.

**Comment by sew268** [comment]
Okay - it only took a few minutes before it all came back to me. :) 
@cappadona @tap87 the issue with Booked lies in the calendar restrictions.  You cannot apply different schedules/calendars to different rooms; it has to be one default schedule that applies to all rooms/resources.  
You can add blackout times to by a date range which is fantastic but this creates a workflow issue when it comes to B30A & B in particular.  What we'd like to do is create a semester long blackout for the basement classrooms from 10PM-Midnight, Monday through Thursday.  When we attempt to then add particular holidays where there would be no reservations all day - for example, Thanksgiving - Booked denies the request because it can't honor 2 blackouts on a particular day.  
What we can do is manage the B30A & B calendars on a monthly basis and manage blackout dates that way but it would be a decent amount of work on our end.  
This might warrant a meeting to discuss since I probably didn't explain it very well but we'd love to know if there is a way to configure booked so that it operates a little more like LibCal with calendar templates and how they manage exceptions.

**Comment by sew268** [comment]
@cappadona @tap87 - okay, it looks like there might be a new feature (I swear it wasn't there before!) that is now allowing for different schedules to be applied to different rooms.  Tobi & I are going to test this out and hopefully we'll be sucessful.  We'll keep you posted but, for the moment, no need for a meeting.

**Comment by cappadona** [comment]
@cul-it/mann-website Sounds good. FYI, what you're seeing could be a new featured introduced with `v2.6`.

**Comment by cappadona** [comment]
Won't fix....Booked is out. See #458.
