### ISSUE TITLE
Identify curated list of event types for events

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#307]

**Comment by sew268** [comment]
Alrighty - here's our list:

Author Appearance
Class/Workshop
Conference/Workshop
Exhibit
Lecture
Meeting
Presentation
Seminar
Special Event
Tour

Let us know if you need anything else!

**Comment by tap87** [comment]
@sew268 Do we want to use 'Class/Workshop' for events from R25 for Basement classrooms?

**Comment by sew268** [comment]
@tap87 Yes, I think that makes sense; that would cover 98% of what happens in those rooms

**Comment by cappadona** [comment]
This is baked. Will be implemented in #415.

**Comment by eeh53** [comment]
These have been added to the back office, with the following additions:

- Information Session
- Fundraiser
- Webinar
