### ISSUE TITLE
Request a purchase form

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#311]
http://mannlib.cornell.edu/contact-us/request-purchase

**Comment by tap87** [comment]
@sew268 @eeh53 Looking at the [current form](http://mannlib.cornell.edu/contact-us/request-purchase), do we want to group certain fields on the same row. You can look at [some examples here](http://semantic-ui.com/collections/form.html).

**Comment by cappadona** [comment]
@tap87 I think that's a good idea, and you should take a first pass. It will be interesting to see how the semantic-ui grid/columns intermingle with Susy.

**Comment by tap87** [comment]
I took a first pass on grouping form fields, deployed to dev.

**Comment by cappadona** [comment]
@tap87 This is looking good. I think this form was meant to live at `use/collections/recommend-a-purchase`. Hopefully @eeh53 & @sew268 can verify.

Also, we'll want to [remove the hyphens](https://github.com/cul-it/mann-wagon/pull/321/commits/438596fce5ca6e61ebd214c2d0b3554f14421775#diff-31ec8683cb13d08d88d1dff1000b25b1R2) from the page title. Thanks.

**Comment by tap87** [comment]
@cappadona Thanks for the information. I will fix the title.

**Comment by tap87** [comment]
@sew268 @eeh53 This form is up on dev, [try it out ](http://dev.mannlib.cornell.edu/request-a-purchase). On successful submission, a content type will be added to the backend, under models->purchase requests

**Comment by sew268** [comment]
@tap87 This looks great!  Couple things I'd suggest: I love the calendar for selecting the publication date but I'd like it to be easier to adjust the year than it is from the calendar; I also noticed that if you mistype the year (no use of the calendar to set the date) you can't move the cursor to the number that you mistyped, you have to delete the year in it's entirety (not a huge deal but I think this could be frustrating for people); I tested a couple of the required fields and noticed that while the phone number field let me readjust my entry to meet the requirements, the email field didn't recover.  For example, I tried just typing my net id - sew268 - and was told that wasn't a complete email. So I added the '@cornell.edu' to my net id and tabbed to the next field but I was still told that my email wasn't complete/valid.  I can show you if this is confusing.  

And we'll want to change the content of the email that is sent to the person who requests a purchase.  

Yes this form should live in the footer and from the mega menu at 'recommend a purchase' under collections.  

@eeh53 we can look at this together again today and see if there's anything else that needs tweaking.

**Comment by eeh53** [comment]
We decided not to use content types for this form.

**Comment by eeh53** [comment]
We're also wondering if we need a separate form, when it looks like the CUL page has a form that collects all the same data as our form: https://www.library.cornell.edu/services/request/recommend

**Comment by cappadona** [comment]
As we discussed today, perhaps our version of the form exists so that non-Cornell patrons can submit a request. The CUL form is behind CUWebAuth.

**Comment by cappadona** [comment]
Sara heard back from Michael who confirmed that we should use the CUL form, so closing this as `wontfix`

**Comment by cappadona** [comment]
So, for real, we are are going to use the CUL form. We'll add a note on our site (`/use/collections/recommend-a-purchase`) that says something along the lines of needing a Cornell NetID to use the form and suggest that the patron uses the site feedback form to recommend a purchase if they don't have a NetID.

**Comment by eeh53** [comment]
I have added the note about using the CUL Recommend a Purchase form using your Cornell NetID and password. However, I would also like to add a link to the Mann website feedback form, so I won't be able to do that until we have that form - #371
