### ISSUE TITLE
Template for staff directory

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#318]

**Comment by cappadona** [comment]
Deployed to dev. Not rendering properly at the moment due to the [inclusion of full semantic-ui styles](https://github.com/cul-it/mann-wagon/pull/321#discussion_r64937915).

**Comment by tap87** [comment]
@cappadona I just pushed a [commit](https://github.com/cul-it/mann-wagon/commit/817defb849e228e4989804915146988d14dacc52) to fix this, I only needed the checkbox component.

**Comment by cappadona** [comment]
Perfect...thanks!
