### ISSUE TITLE
Rethink mega menu categories based on usability feedback

### ISSUE THREAD

**Issue by eeh53** [cul-it/mann-wagon#323]

**Comment by sew268** [comment]
![ia2](https://cloud.githubusercontent.com/assets/14821406/16009929/cb52767e-314c-11e6-9ba5-50214870f333.jpg)

**Comment by eeh53** [comment]
I have the updated mega menu in this Google spreadsheet:

https://docs.google.com/spreadsheets/d/12I0MdkZrm_aatUrHttLdJNn5r-RfPfiGZnUXI-Zmi10/edit?usp=sharing
