### ISSUE TITLE
Template for course reserves

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#324]
Select list (dropdown) with same functionality as [current site](http://mannlib.cornell.edu/library-services/borrowing-delivery/course-reserves).

**Comment by cappadona** [comment]
Deployed to dev.

Some screenshots to show the availability status options:

<img width="1250" alt="screenshot 2016-09-21 10 26 50" src="https://cloud.githubusercontent.com/assets/409842/18716874/48ff36e6-7fec-11e6-810d-8b2bdca04498.png">

<img width="1250" alt="screenshot 2016-09-21 10 02 50" src="https://cloud.githubusercontent.com/assets/409842/18716879/4f08453c-7fec-11e6-934b-45ff896953f8.png">

**Comment by cappadona** [comment]
I'm thinking it would be preferable to keep the course select at the top of the page above the overview info, as [we do now](http://mannlib.cornell.edu/library-services/borrowing-delivery/course-reserves).

If others agree, this will require a change to our layouts as we currently don't have the ability to insert dynamic content before/above the page content.

**Comment by eeh53** [comment]
@cappadona I agree with you. I know we've trimmed the text content on this page a lot, but I still think it would be better to have the course select at the top of the page. 

So do we need to add an issue for changing our layouts so we can insert dynamic content above text content?

**Comment by eeh53** [comment]
@cappadona Also, and you may already know about this, but I just noticed some funky rendering for some reserve titles that are long and run into the text in the "Author" column. Check out BIOMG 2800 for a good example.

**Comment by cappadona** [comment]
@eeh53 I just created #565 to address rendering dynamic content above the page's own content.

I am aware of some tightness in columns at smaller breakpoints and just added #566 as well. Thanks!
