### ISSUE TITLE
Prototype new homepage design

### ISSUE THREAD

**Issue by eeh53** [cul-it/mann-wagon#326]

**Comment by sew268** [comment]
[Homepage.pdf](https://github.com/cul-it/mann-wagon/files/311929/Homepage.pdf)

**Comment by cappadona** [comment]
Adding screenshot teasers. Will send link via HipChat for full experience so you can provide feedback.

<img width="375" alt="screenshot 2016-06-15 13 58 06" src="https://cloud.githubusercontent.com/assets/409842/16091535/1664dbfa-3302-11e6-915c-eb1aea90d6ad.png">

<img width="1234" alt="screenshot 2016-06-15 14 01 36" src="https://cloud.githubusercontent.com/assets/409842/16091540/1dabbf46-3302-11e6-8411-d382cc22f16e.png">
