### ISSUE TITLE
Experiment with modifications to single search to promote Mann results

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#33]
> https://issues.library.cornell.edu/browse/MANNWEB-170.

> Sub-task of https://issues.library.cornell.edu/browse/MANNWEB-151 -> #27

**Comment by cappadona** [comment]
#### Reference

* [single search app](https://github.com/cul-it/single-search)
  * built using [bento_search](https://github.com/jrochkind/bento_search) gem
  * also recommend reviewing [QuickSearch](https://github.com/NCSU-Libraries/quick_search) from NCSU 
* ["new" catalog](https://github.com/cul-it/blacklight-cornell)
  * powered by [blacklight](https://github.com/cul-it/projectblacklight/blacklight)

**Comment by cappadona** [comment]
Now that single search is merged into the catalog, the project we would want to branch is [blacklight-cornell](http://github.com/cul-it/blacklight-cornell) **IF we deteremine** that customization at this level is necessary.

**Comment by cappadona** [comment]
One more note for now, the website results for the single search are provided via a paid [Google Site Search](https://www.google.com/work/search/products/gss.html) engine.

**Comment by tap87** [comment]
@cappadona What spaces/properties are you referring to?

**Comment by cappadona** [comment]
I'm referring to any of our sites or applications that are currently not part of the mannlib.cornell.edu Drupal site proper. Some examples include:

* online exhibits (http://exhibits.mannlib.cornell.edu - collection of PHP sites)
* haiku (http://haiku.mannlib.cornell.edu - Wordpress)
* smartmap (http://smartmap.mannlib.cornell.edu - PHP/CodeIgniter)

Note that all three examples provided are subdomains of mannlib.cornell.edu, so in theory any of these should be targeted if we change the value of the `site:` search operator to `*.mannlib.cornell.edu`. I think most of our web properties follow this pattern, and maybe we can update any stragglers to follow suit if we end up using this approach.

**Comment by eeh53** [comment]
Based on discussion from 3/14/16, decided to implement search with two options: Mann site search and single search.

**Comment by cappadona** [comment]
It was decided during our March 2017 sprint that we would not attempt to modify/fork single search. More details in the issues linked in Tobi's previous comment. Tabling for now.
