### ISSUE TITLE
Libcal rooms availability always show unavailable

### ISSUE THREAD

**Issue by tap87** [cul-it/mann-wagon#337]
because of the restriction on making reservations less than 30 minutes out.

**Comment by cappadona** [comment]
@tap87 Anything change recently? Just noticed that almost all of the LibCal rooms (minus the Hive, which has no hours during the summer) are showing available right now, less than 30 minutes before closing.

<img width="500" alt="screenshot 2016-06-09 17 31 35" src="https://cloud.githubusercontent.com/assets/409842/15947188/4532ecae-2e68-11e6-9446-2ddd36bf3ad9.png">

**Comment by tap87** [comment]
@cappadona It looks like the libcal response doesn't get update till 2 minutes past the current slot. So, you see rooms available for a minute or two. I checked at 8:31 am, and the api was showing the 8:30 - 9 slot available till 8:32 am.

**Comment by cappadona** [comment]
That explains what I saw...thanks @tap87!

**Comment by cappadona** [comment]
Check out Tahir's comment from [#330](https://github.com/cul-it/mann-wagon/issues/330#issuecomment-225960022). During today's meeting he suggested changing the **Users must book** field to `Before Slot's Ending Time` as a potential solution. Tobi is going to confer with her peeps.

**Comment by tap87** [comment]
@cappadona I haven't implemented the logic for the slot's ending time in the code yet, which is why it is still showing unavailable. @eeh53, @sew268, you have set the right field and you can confirm that by clicking reserve, it will show the slot if it is available now.

**Comment by cappadona** [comment]
Thanks @tap87. I just assigned this to you.

**Comment by tap87** [comment]
deployed to dev
