### ISSUE TITLE
When closed, next open logic misses scenario where we haven't opened yet today

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#338]
Check out the screenshot. Taken 7:49am 6/10/16, prior to 8am opening, and the header is reporting that we're next open at **1pm tomorrow**.

<img width="1287" alt="screenshot 2016-06-10 07 49 49" src="https://cloud.githubusercontent.com/assets/409842/15963514/a1f51f16-2ee0-11e6-89f4-190b81ca9b2c.png">

**Comment by cappadona** [comment]
Next open logic was part of #155.

**Comment by tap87** [comment]
Thanks @cappadona for catching that, should be fixed soon.

**Comment by tap87** [comment]
@cappadona This has been fixed, check [this commit](https://github.com/cul-it/mann_liquid_extensions/commit/5ecae21d516c493259853c8dcdb0f815be3b0982). I have also update the ref for the gem in both wagon and locomotive.

**Comment by cappadona** [comment]
Thanks @tap87. Looking good. I don't think we need the day qualifier if the open time is today, at least that's how we do it on the current site. We can discuss this next week...

**Comment by eeh53** [comment]
We decided that we don't need the day qualifier if the open time is today.
