### ISSUE TITLE
Review information architecture and identify key areas to handoff to CUL content

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#34]
https://issues.library.cornell.edu/browse/MANNWEB-171. Sub-task of https://issues.library.cornell.edu/browse/MANNWEB-138

**Comment by eeh53** [comment]
[CUL content.xlsx](https://github.com/cul-it/mann-wagon/files/123677/CUL.content.xlsx)

**Comment by sew268** [comment]
Can close this and link to #19?
