### ISSUE TITLE
Add all public machines to LabStats

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#340]
Currently covered:

* B30 A
* B30 B
* Stone Classrooms

Missing:

- [x] Stone Computing Center (PCs and Macs)
- [x] McManus Balcony (Macs)
- [x] ~~anything else?~~ nope!

> I do see 40 `LIB-PAC-PXX` *unassigned* machines in LabStats, so perhaps some of the Stone Computing Center PCs are already running the LabStats client?

**Comment by grp44** [comment]
I organized the Research computers in a Labstats group called "Research Computers".

**Comment by grp44** [comment]
I installed Labstats 6 clients on all of the 3rd Floor IMacs. I created a group in Labstats called "Research IMacs (3rd Floor Study Area)"

**Comment by grp44** [comment]
I installed Labstats 6 clients on 6 1st Floor IMacs. I created a group in Labstats called "Research IMacs (1st Floor Study Area)". I will install the other 6 Labstat Clients next week.

**Comment by cappadona** [comment]
Thanks for the update, Gabriel. I've updated and deployed all of the corresponding logic to address these additions, so the numbers should reflect your progress as you add the client to the rest of the machines.

**Comment by cappadona** [comment]
Hey @grp44. Here's the current totals for each location that we currently have tracked in LabStats:

* B30A: **44**
* B30B: **31**
* Stone Classroom: **27**
* CIT 112: **26**
* CIT Mac 220A: **22**
* CIT 101: **15**
* Research PC: **40**
* Research Mac: **11**
* McManus: **5**

I know you said you have a handful of machines down right now for repairs, so let me know if you think these numbers accurately reflect reality at the moment.

Here's a snapshot of the full details for the current status of public machines:

```json
{
  "Name": "Mann Library",
  "Groups": [
    {
      "Label": "B30A",
      "InUse": 30,
      "Available": 13,
      "Offline": 1,
      "TurnedOn": 43,
      "Total": 44,
      "OrderNum": 1
    },
    {
      "Label": "B30B",
      "InUse": 0,
      "Available": 28,
      "Offline": 3,
      "TurnedOn": 28,
      "Total": 31,
      "OrderNum": 2
    },
    {
      "Label": "Stone",
      "InUse": 1,
      "Available": 23,
      "Offline": 3,
      "TurnedOn": 24,
      "Total": 27,
      "OrderNum": 3
    },
    {
      "Label": "CIT 112",
      "InUse": 0,
      "Available": 25,
      "Offline": 1,
      "TurnedOn": 25,
      "Total": 26,
      "OrderNum": 4
    },
    {
      "Label": "CIT Mac 220A",
      "InUse": 3,
      "Available": 19,
      "Offline": 0,
      "TurnedOn": 22,
      "Total": 22,
      "OrderNum": 5
    },
    {
      "Label": "CIT 101",
      "InUse": 1,
      "Available": 11,
      "Offline": 3,
      "TurnedOn": 12,
      "Total": 15,
      "OrderNum": 6
    },
    {
      "Label": "Research",
      "InUse": 10,
      "Available": 21,
      "Offline": 9,
      "TurnedOn": 31,
      "Total": 40,
      "OrderNum": 7
    },
    {
      "Label": "Research Mac",
      "InUse": 2,
      "Available": 2,
      "Offline": 7,
      "TurnedOn": 4,
      "Total": 11,
      "OrderNum": 8
    },
    {
      "Label": "McManus",
      "InUse": 1,
      "Available": 1,
      "Offline": 3,
      "TurnedOn": 2,
      "Total": 5,
      "OrderNum": 9
    }
  ],
  "InUse": 48,
  "Available": 143,
  "Offline": 30,
  "Total": 221
}
```

**Comment by grp44** [comment]
Looks correct to me. I will be bringing the IMac to the Cornell store to be sent out for repair next week, so hopefully we will have all the systems up and running soon. I will keep you posted.

**Comment by cappadona** [comment]
Hey @grp44, just checking in on the status of this. When you reached out via email last week it sounded like we were close. Here's a list of the anomalies I'm currently seeing in the LabStats dashboard:

* Research PCs -- **12 offline**, total of 39 when expecting 40 (there is one machine in the unassigned group, `LIB-PAC-DS-01`)
* Research Macs -- **7 offline**
* McManus Macs -- **all 5 offline**
* Stone Classroom -- **26 offline**

**Comment by cappadona** [comment]
Hi @grp44. The numbers are looking a lot better today. Maybe you've worked on this? Here's the latest anomalies:

* Research PCs -- **6 offline**, total of 39 when expecting 40 (there is one machine in the unassigned group, `LIB-PAC-DS-01`)
* Research Macs -- **1 offline**
* McManus Macs -- **0 offline** -- but only 5 total. Should be 6 machines, correct? Is one still out for repairs?
* Stone Classroom -- **1 offline**

**Comment by cappadona** [comment]
Hey @grp44. Me again. Here's the latest stats from today. Will you please comment on this when you get a chance? Would love to close this out.

* Research PCs -- **0 offline**, and total of 39 when expecting 40 (there is one machine in the unassigned group, `LIB-PAC-DS-01`)
* Research Macs -- **3 offline**
* McManus Macs -- **4 offline** -- and still only 5 total. Should be 6 machines, correct? Is one still out for repairs?
* Stone Classroom -- **0 offline**

**Comment by grp44** [comment]
Yes one IMac is out for repair still. The Apple repair process at Cornell took a serious nose dive in the last 2 years so getting anything fixed under warranty is a nightmare. 39 Research/Outside Stone computers is the correct number. People have also been turning off systems as much as ever so far this semester. Other then that all looks good from my end.

**Comment by cappadona** [comment]
Awesome...thanks for the update, Gabe!
