### ISSUE TITLE
Add space categories/groupings under Find a Space in mega menu

### ISSUE THREAD

**Issue by eeh53** [cul-it/mann-wagon#344]

**Comment by cappadona** [comment]
This is going to be a bit trickier than expected because the snippet passed to the `nav` tag doesn't have access to the drops. Adjusting the estimate and back to the drawing board.

**Comment by cappadona** [comment]
If this doesn't work out, I'll add some pseudo child pages to mimic the nav we want, including one for **All Spaces** now that we decided in #368 that we won't be linking the second-level pages in the mega menu.

**Comment by cappadona** [comment]
@sew268 @eeh53 The decision in #368 still stands, correct? I'm about to add an **All Spaces** option...

**Comment by cappadona** [comment]
Deployed to dev
