### ISSUE TITLE
Decide on validation library

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#352]
@tap87 used [`formvalidation`](https://github.com/formvalidation/formvalidation) (jquery plugin) for the [now-defunct](https://github.com/cul-it/mann-wagon/issues/311) request a purchase form. This plugin has been integrated into webpack build as part of #351, but we're thinking we should use semantic-ui's form validation.

More details and back-story in bad4a81.

**Comment by cappadona** [comment]
I think we should go with semantic-ui validation. Reason is two-fold:

1. Dirt simple to use (see #411)

1. `formvalidation` is no longer open source, and would require a license

  > The version we're currently using (`v0.6.1`) is the last version available prior to converting to a [paid license](http://formvalidation.io/download) and is over a year old

**Comment by cappadona** [comment]
Darcy questioned whether semantic-ui's form validation will suffice in #300, so opening this back up for discussion.

**Comment by tap87** [comment]
Semantic UI can handle validation functions, see http://semantic-ui.com/behaviors/form.html#adding-custom-rules
