### ISSUE TITLE
Decide on & implement course reserves link in header 

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#360]
Mockups from #326 introduced a set of favorite/popular pages in the header, based on analytics data:

* course reserves
* spaces
* computers

Go with this or another direction?

**Comment by cappadona** [comment]
Decided to start with only the course reserves link for now

**Comment by cappadona** [comment]
Deployed to dev.

**Comment by eeh53** [comment]
@cappadona Was chatting with Darcy and she had an idea to maybe add a link to Research Guides up at the top next to Course Reserves - might be a nice compromise now that the research guides have come off the homepage, and perhaps putting the link next to course reserves will see them get used a little more.

**Comment by eeh53** [comment]
Oops. Just saw that Darcy added a separate issue for this - #404
