### ISSUE TITLE
Decide on handling of top-level pages

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#368]
Right now they're pretty much empty.

**Comment by eeh53** [comment]
So as of right now, the following top-level nav pages that have content (or will have content) are:

- Find A Space
- Poster Printing
- News (will have content after news content type is created)
- Chat in the Stacks (will have content)
- Events & Exhibits (pre-filtered list on Events page)
- Workshops & Classes (pre-filtered list on Events page)

**Comment by eeh53** [comment]
After looking at what other websites are doing, it looks like it's more common to NOT have the top-level nav pages be "live" pages. And since we don't have too many of those pages with content, we think this might be the better way to go. We may have to add some additional pages and transfer the content that's currently living there (Find a Space and Poster Printing, primarily), but that shouldn't be a huge task.

**Comment by sew268** [comment]
http://library.pdx.edu/services/ adding a link to a site that handles the top-level pages in a way that we like

**Comment by eeh53** [comment]
Our top-level pages (Use the Library, Get Help, and News & Events) 
* collection of images for each child page/second level page
* under each one of those would be a link to their children/third level pages

Our second level pages will just be headings in our mega menu (no content/url)

**Comment by cappadona** [comment]
Just realized we never created an issue for the the work that resulted from this decision. See #460.

**Comment by sew268** [comment]
@cappadona I can create the issue - we'll need to populate the content for those pages that the top nave will take you to and do we need to create a content type as well?

**Comment by cappadona** [comment]
Thanks @sew268 . I already created #460, sorry for the confusion. No content type needed here. The plan is to use layouts and editable elements.

> P.S. I edited my previous comment in an attempt to provide some clarity

**Comment by sew268** [comment]
@cappadona thanks!
