### ISSUE TITLE
Book a Consultation button per librarian in meet-librarian for v1.0

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#372]
For both the home page and experts as well.

If we're going ahead with this, we'll need to create sub-tasks.

**Comment by cappadona** [comment]
Still undecided on this for `v1.0`. Definitely keeping it around for the staff usability testing next week.

**Comment by cappadona** [comment]
@eeh53 We've got the green light for this, correct? Will you add brief details here when you get a chance so we can plan accordingly?

**Comment by cappadona** [comment]
Now I'm hearing this might be off the table once again...@sew268 or @eeh53, will you confirm one way or the other when you get a chance? Thanks.

**Comment by eeh53** [comment]
@cappadona I had a chance to talk to Tom O. yesterday, and it sounds like they're going to proceed with this plan, despite the challenge of not being able to sync their Outlook and LibCal accounts. There is a meeting next Wednesday, 9/21, for all the reference staff, which I will attend. At this meeting, we (Camille and I) will show reference staff how to set up their LibCal calendars and then the department will talk through what the workflow will be. I will report back after that meeting.

**Comment by cappadona** [comment]
Thanks for the update, @eeh53. Just removed the question mark from the issue title to reflect the status. Moving this to `Oct` milestone.

**Comment by eeh53** [comment]
@cappadona The training session went well and the librarians would be willing to try this feature for v. 1 (meaning they will all work on getting their availability set up in My Scheduler).

**Comment by cappadona** [comment]
Thanks for the update @eeh53.

To address a dedicated widget per applicable staff member on the pages you identified, I see this breaking down to two tasks, described in #322 & #560.

As for utilizing a My Scheduler widget elsewhere on the site that would list all applicable librarians/staff, LibCal does support this and I see that we already have a **Mann Library** group defined:

![screenshot 2016-09-21 17 01 04](https://cloud.githubusercontent.com/assets/409842/18728846/1b67af7a-801d-11e6-93ea-9f6f22fc4a3e.png)

If think we should add an issue for this and discuss feasibility for `v1.0` at our next meeting.

**Comment by eeh53** [comment]
We've decided to hold off on having the group consultation/MyScheduler widget for v. 1 - it needs more thought on how it would work within the IA.
