### ISSUE TITLE
Prototype calendar/availability workflow for Booked reservations

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#386]

**Comment by dbranchini** [comment]
Is this a new feature?  The current site does this, correct?  It's not ideal and separated from the reservation page, but you can get a calendar of events/workshops booked, which then indicates what is available.  Or is "new feature" being used in a different context?

**Comment by cappadona** [comment]
I've been using the `new feature` tag to indicate something that does not yet exist on the new site. We can change that up if you prefer to use it to identify planned/suggested features that aren't found on our current site.

**Comment by tap87** [comment]
https://docs.google.com/spreadsheets/d/1nq5zXXHC8r1XTVfODcq-PAs4jWFizWacZP2CLhcogPw/edit?pref=2&pli=1#gid=186001220

**Comment by cappadona** [comment]
Booked is out, so this is a non-issue.
