### ISSUE TITLE
Utilize existing software table 

### ISSUE THREAD

**Issue by sew268** [cul-it/mann-wagon#399]
Need to bring http://mannlib.cornell.edu/equipment-software/software into the new site

**Comment by cappadona** [comment]
This will involve parsing a `csv` file. Currently [happens in php](https://github.com/cul-it/mann-softwarelist/blob/5f06cdd7cca816ddd2ab777ad09aadcfdafbdd9f/softwarelist.module).

**Comment by cappadona** [comment]
Deployed to dev.
