### ISSUE TITLE
Prototype interaction for room/space reservation from sketches

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#40]
https://issues.library.cornell.edu/browse/MANNWEB-187. Sub-task of https://issues.library.cornell.edu/browse/MANNWEB-126

**Comment by cappadona** [comment]
@eeh53 @sew268 Is this issue here because of the reservation button in the upper right of the events page?

**Comment by eeh53** [comment]
Closing this issue since we decided to remove the reservation button from the upper right corner of the events page.
