### ISSUE TITLE
Add employment page

### ISSUE THREAD

**Issue by dbranchini** [cul-it/mann-wagon#402]
Will this be driven by a content type or is there a Workday API that we can pull this content from?  If it's a content type, then who is responsible for maintaining.

**Comment by eeh53** [comment]
Link to CU employment page for external applicants

Student employment info need to be updated

**Comment by sew268** [comment]
@eeh53 Not thrilled with this but I've added the content for employment...is it weird that the menu only lists student employment??

**Comment by cappadona** [comment]
Maybe just list the student employment on the main employment page instead of creating sub-pages for each division that hires students?

How often do we have student job postings?  Would it make sense to have a content type for them?

**Comment by sew268** [comment]
I guess you're right, I could just list everything on one page.  Let me think about a content type...

**Comment by sew268** [comment]
ok changes made so that all areas for student employment are listed together
