### ISSUE TITLE
Clean up and update text on existing Mann webpages

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#41]
https://issues.library.cornell.edu/browse/MANNWEB-188. Sub-task of https://issues.library.cornell.edu/browse/MANNWEB-129

**Comment by eeh53** [comment]
This is mostly complete at this point, though we are still waiting on a few last pages to be updated (so we can migrate that content to the new website). Will be sending reminders to Michael and Eveline this week to see where they are with this.

**Comment by cappadona** [comment]
Hey @eeh53 @sew268. The plan was to keep this baked for a bit until we can create new issues to track the content updates from Michael and Eveline, correct? If that's already happened, will you link them up and close this? Thanks.

**Comment by cappadona** [comment]
Looks like #43 might cover Michael and #42 at least partially covers Eveline?
