### ISSUE TITLE
Add space between last line of content and footer

### ISSUE THREAD

**Issue by dbranchini** [cul-it/mann-wagon#412]
This is an example where I think it would help -- http://dev.mannlib.cornell.edu/use/collections/print, but also the home page.  I keep feeling like "meet all our experts" goes with the footer instead of the content above it.  Another potential solution for that particular case is to bring that up (next to the heading) for that section.

**Comment by cappadona** [comment]
Let's add some top padding/margin to the footer

**Comment by cappadona** [comment]
Deployed to dev.
