### ISSUE TITLE
Primary/Main navigation - buttons (look) on hover over

### ISSUE THREAD

**Issue by dbranchini** [cul-it/mann-wagon#413]
On the primary navigation, if a user hovers over an option, the link looks like a button.  I'm not a fan. Others on the team might feel differently, so I wanted to capture it and have a conversation about it.  If the button sticks with the team, then I'd suggest adding padding to the left of the option (seems really close to the left edge with a ton of space to the right -- of course screen size effects real estate so that does make a difference too) and/or a lighter/softer approach instead of the big contrast it has now with the background.

**Comment by eeh53** [comment]
More contrast in mega menu with the blue and the black

**Comment by cappadona** [comment]
Updated palette deployed to dev, which includes tweaks to this look. Let me know if this still doesn't work for you @dbranchini.
