### ISSUE TITLE
Normalize and upload new staff photos (plus retakes)

### ISSUE THREAD

**Issue by dbranchini** [cul-it/mann-wagon#428]
Jenny redid a few staff photos (because staff asked her to) plus she took a few more.  Workflow?  It probably doesn't make sense for Tobi to upload these because they need to be normalized first.

**Comment by eeh53** [comment]
@dbranchini Oh crud. I uploaded the new photos before I saw this comment. I added photos for 

- Nick Cappadona
- Megan Benson

and uploaded new photos for

- Keith Jenkins
- Rebecca Younes
- Gabriel Plaine

Sorry to screw up the workflow here.
