### ISSUE TITLE
Use iCal feed for room reservations in libcal for events page

### ISSUE THREAD

**Issue by tap87** [cul-it/mann-wagon#434]

**Comment by sew268** [comment]
@tap87 event types have been added

**Comment by tap87** [comment]
@sew268 Thank you.
On another note, the iCal feed from libcal that we want to use for events contains the patron info (name and email of person making reservation). I was able to remove the email from eventId field since we will be using that in the url for a single event. Not sure if we need to worry about privacy of patron info here.
