### ISSUE TITLE
Customize LibCal confirmation emails consistently for all spaces

### ISSUE THREAD

**Issue by eeh53** [cul-it/mann-wagon#441]
e.g. tech support request

**Comment by sew268** [comment]
@cappadona working my way through these and they're almost ready for Tobi to review.  One thing that I've noticed (and wish that I could do something out) is that I can't apply any styling: no bulleted list, bold any type, or insert a hyperlink.  
You haven't seen or noticed anything that might allow us to do that, have you?  I think I know the answer but I'm holding out hope

**Comment by cappadona** [comment]
@sew268 I haven't noticed anything like that, but I also am not very familiar with the email confirmation feature in LibCal. I can take a look, but in the meantime it might not hurt to ask Springshare support.
