### ISSUE TITLE
Determine how to provide staff with ability to mark duplicate events/bookings in LibCal

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#443]
Staff need to be able to mark data from LibCal as duplicate of Localist event if necessary. We're thinking of using the `Notes` field which is only available from the LibCal admin and is included in the iCal feed as `Internal Notes` if populated.

**Comment by eeh53** [comment]
revisit notes field

**Comment by sew268** [comment]
Found it!  This is possible from the Admin side, after the reservation has been made and approved.  The existing reservation can be clicked on and then text can be added in the notes field.

**Comment by cappadona** [comment]
Great, now we just need to settle on the string we want to add to the notes field if we want the event omitted from the mann website. I'll throw the first suggestion into the ring: `hide-mannweb`.

**Comment by sew268** [comment]
@cappadona I wonder if something like duplicate-mann might be easier for folks to remember?  Since they're going in and modifying the duplicate??  Tobi was thinking along the same lines as me but ultimately, whatever we tell them to enter is fine

**Comment by cappadona** [comment]
`duplicate-mann` works for me. Now we just need a demo of how to reach this elusive notes field from within the LibCal API ;)

**Comment by sew268** [comment]
added a new custom field to booking form for lobby, conference rooms, and classroom so that staff can enter the `duplicate-mann` string.  Can also be done from the admin side.

**Comment by cappadona** [comment]
@tap87 Change of plans. Sara just met with Matt & Jimmy and there were some concerns regarding the use of the `Additional Notes` field on the LibCal reservation forms. I can fill you in on the details if you're interested, but as a result, we're switching gears and going with a new field:

Label: `Will this be advertised through Cornell Events?`
Options: `Yes`, `No`, `Don't know`

We want to test for `Yes` and filter out when truthy. Moving #666 back to the oven so you can re-implement. Sorry...

**Comment by sew268** [comment]
@tap87 thanks for being flexible and changing this up at the last minute.  This seems to be working though I've found bug which I'm going to create a separate issue for.

**Comment by cappadona** [comment]
Back in the oven because there's one more item on our wish list to making this awesome -- _or at least usable_ ;) #672
