### ISSUE TITLE
Add month view option for Mann Library hours

### ISSUE THREAD

**Issue by eeh53** [cul-it/mann-wagon#447]

**Comment by tap87** [comment]
LibCal doesn't provide an API endpoint for monthly data, only widget for monthly or combined weekly/monthly view.

**Comment by sew268** [comment]
@tap87 so then are we going to provide a link to the widget?  How do we plan to integrate some way to see a month at a glance?

**Comment by tap87** [comment]
We can embed the widget on the page. Although I am not sure we want to use it, it looks pretty confusing with all the departments showing. We can only change the colors and text alignment on the calendar.
You can preview it at http://spaces.library.cornell.edu/admin_hours_widgets.php. Select "Mann Library" and click "Generate Code/Preview".

**Comment by sew268** [comment]
@tap87 so there is no way to parse out just Mann Library?  Is there something other than LibCal we can use to get this monthly view?  We could add a 2nd Mann library location that would only contain buiding hours but that requires more work for staff on a regular basis and I'm reluctant to go that route with all that we're adding back on everyone's plate by going with LibCal.

**Comment by tap87** [comment]
@sew268 There is not way to get Monthly view for Mann Library only in the widget. But we can hide the departments in the script/css. And we can style it the way we want.

**Comment by cappadona** [comment]
Decision from todya's meeting: Let's use the widget and show only the library and lobby.

**Comment by tap87** [comment]
@cappadona I merged the hourly widget code, PR #472. It needs a lot of styling, see the widget preview in LibCal for all the styling options.

**Comment by cappadona** [comment]
Styled and deployed to dev. Could use some tweaking ([abbreviated days of week](https://github.com/cul-it/mann-wagon/pull/519/commits/798686b5712ffe4a9ab93952c8d56a48c338add6)) for mobile.

Also added #520 as improvement to current behavior of switching between weekly and monthly views.
