### ISSUE TITLE
Open external links in new window

### ISSUE THREAD

**Issue by eeh53** [cul-it/mann-wagon#450]

**Comment by eeh53** [comment]
Right now, this will only apply to links from mega menu, header & footer.

**Comment by cappadona** [comment]
Deployed to dev.

### Please Note
The automatic handling in the megamenu and other nav builders relies on internal redirects to use `root level` URLs.

> i.e. `/course-reserves` for `/use/borrow-request-renew/course-reserves` and not `http://dev.mannlib.cornell.edu/course-reserves`

This is kinda/sorta related to #496. Questions? You know where to find me :)
