### ISSUE TITLE
Add slight delay and indicator arrows to mega menu 

### ISSUE THREAD

**Issue by eeh53** [cul-it/mann-wagon#451]

**Comment by dbranchini** [comment]
Tim forwarded me this example of a primary menu from Caltech - http://www.caltech.edu/.  I like the behavior (not the styling) and it made me wonder if this is a good solution to the problems we witnessed during user testing.  What do others think?  Appears to be a slight delay on the hover over, but also works on click (as well as on click removes it from view).

**Comment by cappadona** [comment]
Initial attempt at this has been deployed to dev. Please chime in with your thoughts.

Leaving this open since, as I stated in the [commit message](https://github.com/cul-it/mann-wagon/commit/99d344e), this current implementation doesn't work for touch devices.

**Comment by cappadona** [comment]
We discussed this today and all agreed that the latest changes have improved the experience to an acceptable rating ;)

Closing out for now. Touch devices will be addressed in #500.
