### ISSUE TITLE
Update existing SmartMaps and Floorplans

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#46]
> https://issues.library.cornell.edu/browse/MANNWEB-198.

> Sub-task of https://issues.library.cornell.edu/browse/MANNWEB-129

**Comment by sew268** [comment]
Updated and useable now : http://smartmap.mannlib.cornell.edu/floor/0

Down the road, it would be nice to epxlore options like http://library.queensu.ca/library/floorplans/

**Comment by cappadona** [comment]
Confused...are we all set this now that the smartmap has been updated?

**Comment by sew268** [comment]
Um, huh - what was I thinking there....I guess there was a lot of functionality that we wanted to add, isn't there?  There were features for how we could label areas and potentially highlight that would be great to have so - shall I delete my last comment? :)

**Comment by cappadona** [comment]
Ha...no worries. I wouldn't delete your previous comment, but it would be good to elaborate/define what we want to accomplish here and then potentially create additional issues if necessary.

It would be best to do that elaborating/defining by editing the first comment on the issue...maybe adding a checklist of items above the Jira links?

**Comment by eeh53** [comment]
Sara will review floor maps. Wendy has made some updates already. Still need to add:
- [ ] iMacs on 3rd floor balcony

**Comment by sew268** [comment]
After review the only addition needed is the iMacs.  Talked to Wendy and she will make the change shortly.
