### ISSUE TITLE
Accessibility scan

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#464]

**Comment by dbranchini** [comment]
Here's an option that I think might work.  It can be used as a Chrome extension - http://wave.webaim.org/extension/ - or you can use their website, but either way, pretty sure you need to go page by page.  I think you might see patterns though quickly that can be addressed site wide.

**Comment by dbranchini** [comment]
I was able to run a quick scan on the home page using AccessLint (pretty sure this is the one that Nick mentioned) and here's the results - http://accesslint.com/results?url=http%3A%2F%2Fdev.mannlib.cornell.edu%2F&commit=Analyze.  Again, would need to done page by page.  I'll keep looking for something that is more comprehensive.

**Comment by cappadona** [comment]
Thanks Darcy...that is the one I mentioned and didn't realize they had an online tester.

**Comment by cappadona** [comment]
Didn't get to this...back to thawing.

**Comment by cappadona** [comment]
Level A addressed by #883 #907.

**Comment by cappadona** [comment]
Level AA addressed by #906. Everything deployed to dev & prod.
