### ISSUE TITLE
String LibCal booking slots together

### ISSUE THREAD

**Issue by tap87** [cul-it/mann-wagon#473]
Related to #434 The bookings are done using 30 minute slots in LibCal, need to account for that for a booking with same title/description.

**Comment by tap87** [comment]
Done, see [commit](https://github.com/cul-it/mann-wagon/commit/8fda9a29eac1cd1df22d1c2963e00c01f9e4105e)
@cappadona This needs to be deployed.

**Comment by cappadona** [comment]
Just deployed this 👍

**Comment by tap87** [comment]
Thanks @cappadona. I also pushed a couple of commits fixing the ordering of events on the homepage, and removing past LibCal bookings from default view.
