### ISSUE TITLE
Consistency/standards for spotlight images

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#481]
If you take a look at the initial 3 sample images, they each have the Cornell University lockup with Albert R. Mann Library, which is really meant for print.

In my opinion, this is overkill and should be dropped, but if we decide to keep it, maybe we should at least suggest that the digital logo is used and placement/size is consistent.

**Comment by eeh53** [comment]
Nick talked to Jenny about this during staff feedback section and agreed that it wasn't necessary to add Cornell/CUL insignia to spotlight featured images. 

This would be good to include in future style/content editing guide.
