### ISSUE TITLE
Design architecture and workflow for hours management & delivery

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#49]
https://issues.library.cornell.edu/browse/MANNWEB-224

**Comment by tap87** [comment]
The following two diagrams were an initial concept of the architecture and the workflow for the hours service. The architecture diagram will need to be modified to reflect the existing middleware used to render the hours.

![mannlib-hours-architecture](https://cloud.githubusercontent.com/assets/4334244/12918061/f9135c6c-cf0a-11e5-93ca-3dcb28bc51a7.png)
![mann-hours-workflow](https://cloud.githubusercontent.com/assets/4334244/12918062/f915ac7e-cf0a-11e5-9753-8e782ca1128a.png)

**Comment by tap87** [comment]
The architecture diagram for the hours service in Locomotive wagon/engine, and detailed diagram for the custom gem to render liquid drops in Steam:
![hours architecture_page_1](https://cloud.githubusercontent.com/assets/4334244/12984339/395dc12a-d0bb-11e5-9151-ec051c38472a.jpg)
![hours architecture_page_2](https://cloud.githubusercontent.com/assets/4334244/12984338/3959f69e-d0bb-11e5-80a3-5ab2103035f8.jpg)
