### ISSUE TITLE
Add locomotive accounts for form email notifications

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#490]
- [x] site feedback #371 
  * `mann-website-team-l`
- [x] consultation request #301
  * `mann-ref`
  * `nnh5`
  * `tjo65`
- [x] instruction request #300 
  * `klp92`
- [x] software request #298 
  * `mann-pac-help`

**Comment by cappadona** [comment]
@eeh53 @sew268 I just added software request form to the list now that it's live. Do we still need notification emails sent to [both addresses listed above](https://github.com/cul-it/mann-wagon/issues/490#issue-174588353)?

**Comment by sew268** [comment]
@cappadona hmmm, not sure but I'll find out!

**Comment by sew268** [comment]
@cappadona and the answer is....we can remove mann-pac-l

**Comment by cappadona** [comment]
@sew268 Done. Thanks!

**Comment by cappadona** [comment]
All accounts listed above have been created, but are not yet set to receive notifications.

**Comment by cappadona** [comment]
All of the forms have been configured for notifications as spec'd above.
