### ISSUE TITLE
Handle scenario where there are zero active spotlights

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#495]
As originally described in `todo` from 14d3fc7. Should we setup a default placeholder image? Currently, the entire section just drops from the page.

**Comment by cappadona** [comment]
For `v1.0` we'll display two default images only when there are no active spotlights. @sew268 will work on obtaining those default images.

**Comment by cappadona** [comment]
Add boolean field to content type to indicate default/fallback images. Also, segment the back-office display by this field.

**Comment by cappadona** [comment]
Content type & template logic has been updated and deployed to dev. Needs to be be tested by adding default/fallback images and for that I'm passing it back to @sew268.

**Comment by sew268** [comment]
@cappadona added the default spotlight images and...success!  I think I'd like the logic to change so that are always 3 slides in rotation.  So that would mean if there is only 1 active spotlight, then 2 of the default slides would kick in.  If there are no active spotlights, then all 3 default slides would be in rotation.  Does that make sense?

**Comment by cappadona** [comment]
Yes, what you describe makes sense. To recap in an attempt to get some clarification...

### Current behavior
* 5 active spotlights max (no minimum)

* fallback images only kick when there are no active spotlights
  > In other words, there is no mixing of active spotlights and fallback images, it's one or the other

* fallback images are capped at 2 max

### Desired behavior
* 5 active spotlights max

* 3 spotlights min

* If active spotlights < 3, supplement with fallback image(s)
  > **QUESTION:** Supplement only to the 3 minimum total or supplement all 3 fallback images?

* fallback images are capped at 3 max

**Comment by sew268** [comment]
@cappadona your summary looks good and I've added an answer in-line

**Comment by cappadona** [comment]
Thanks for clarifying. Just deployed updated logic to dev. Let me know if I missed anything.
