### ISSUE TITLE
Determine 1-2 default slides for Featured Events spotlight

### ISSUE THREAD

**Issue by eeh53** [cul-it/mann-wagon#502]
Similar to the spotlight carousel on the homepage, we need to determine and set up 1-2 default slides to be feature in the Featured Events carousel so that it never appears empty.

**Comment by cappadona** [comment]
I think it would be reasonable to simply not render this component if there are currently no featured events.

**Comment by cappadona** [comment]
We agreed that we won't render this component if there aren't any featured events
