### ISSUE TITLE
Determine what to do with events with no location (for Localist)

### ISSUE THREAD

**Issue by eeh53** [cul-it/mann-wagon#506]
What’s the X under Space/Room?  It needs to be removed.

**Comment by tap87** [comment]
@eeh53 The x is caused by events that don't have a room associated with them, in the present case, these are 'online' events. How do we want to handle them, should we list 'online' under the location filter? Are there any other events that won't have a room associated with them?

**Comment by eeh53** [comment]
@tap87 Maybe we can add a "location" for these online events? How about "webinar" (that's what Localist uses). I can add it to #307 if we all agree this is the way to go.

**Comment by tap87** [comment]
@eeh53 Sound good to me.
