### ISSUE TITLE
Make Events filters more visually prominent when selected

### ISSUE THREAD

**Issue by eeh53** [cul-it/mann-wagon#508]
Especially problematic when using the canned-filtered links (i.e. `Upcoming Workshops`).

Render the applied filters adjacent to the page title (above the events listing).

**Comment by tap87** [comment]
@eeh53 Need more details on how to implement this. Are we just displaying the filters, or also providing the functionality to remove the filters.

**Comment by tap87** [comment]
@cappadona I have created PR #576, and assigned this issue to you.

**Comment by cappadona** [comment]
@tap87 Will you populate the new content types from #572 on the dev instance with some sample data when you get a chance? Currently we have no filters to work with. Thanks.

**Comment by tap87** [comment]
Ok, I will do that now.

**Comment by cappadona** [comment]
Deployed to dev.
