### ISSUE TITLE
Implement site search for launch

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#509]
[Locomotive's search](https://trello.com/c/ZM8JTvwJ) will not be ready in time. Most likely will go with [Google CSE](https://cse.google.com/cse).

**Comment by eeh53** [comment]
Nick will look into numbers on the existing site to see which tier for the google site search we should subscribe to until locomotive enable site search functionality.

**Comment by cappadona** [comment]
Knocking down the estimate since we did an initial implementation #171.

**Comment by cappadona** [comment]
Switched over to the paid CSE that Sara helped set up. Considering this baked for now, but we should probably revisit indexing and tweaking configuration at some point.
