### ISSUE TITLE
For recurring events in localist, display the selected event date in modal

### ISSUE THREAD

**Issue by eeh53** [cul-it/mann-wagon#511]
For example, go to 10/7 and click on Fabrication Fridays. The expected behavior is to display the selected date.

![invalid date](https://cloud.githubusercontent.com/assets/17053005/18444611/feacada4-78e7-11e6-82c1-9100bad3d573.PNG)

**Comment by eeh53** [comment]
Date should be the date selected (for recurring events).

**Comment by tap87** [comment]
An example of how localist handles recurring events, no matter which date you chose, on the event detail page, the first date is displayed.
Click any of the dates for signal to code: http://events.cornell.edu/calendar?event_types%5B%5D=4205

**Comment by cappadona** [comment]
Thanks for the example, Tahir. I know we've discussed this before, but just to ensure everyone is on the same page, we're not trying to recreate Localist.

I think we should proceed forward with the consensus from yesterday, that the displayed date in the modal for a recurring event should be the date selected by the user.

**Comment by tap87** [comment]
@cappadona I understand we are not trying to recreate Localist, but it is easier to do it that way than to display the selected date.
