### ISSUE TITLE
When closing a modal for a full event, you lose your place in the events app

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#516]
The whole point of the modal was to keep your place in the app. Current behavior results in the exact opposite experience -- you're reset to viewing all upcoming events.

**Comment by cappadona** [comment]
Tahir will verify whether we can keep our place when dismissing the modal, otherwise we'll drop the URL addressable modal.

**Comment by tap87** [comment]
@cappadona I just merged # #554. I had to wrap the [templates in a div](https://github.com/cul-it/mann-wagon/blob/dev/vue/events/homepage-events/templates/homepage-template.html#L1) to prevent the fragment instance errors in vue. In the process, I had to [fix a css margin](https://github.com/cul-it/mann-wagon/blob/dev/src/scss/components/_events-home.scss#L28-L32). Feel free to redo it.

**Comment by cappadona** [comment]
@tap87 Thanks for the heads up. This has been deployed to dev. The top margin is now necessary because of the extra wrapper `div` that was introduced, which breaks the Susy layout.

I understand the need for the wrapper from the Vue perspective (to avoid the fragment instance), but I think a cleaner approach would be to break this down into multiple components, which would also help DRY up `homepage-template.html`:

```diff
diff --git a/homepage-events-exhibits.html b/homepage-workshops-classes.html
index b860188..8e55ec5 100644
--- a/homepage-events-exhibits.html
+++ b/homepage-workshops-classes.html
@@ -1,7 +1,7 @@
<section class="events-home">class="events-home events-home--workshops">
  <h4 class="events-home__heading lead-in">class="lead-in">
    <a class="events-home__heading-link" href="/news-events/events/upcoming">
      Eventshref="/news-events/events/upcoming?eventType=Class/ Workshop">
      Workshops &amp; ExhibitsClasses
    </a>
  </h4>

@@ -11,7 +11,7 @@
    </div>
  </div>

  <template v-for="(date, events) in allEvents | orderBy 'event_start_time' | hideEventTypeeventTypeFilter 'Class/ Workshop' | limitListFilter 3 | groupBy 'event_start'">
    <h5 class="events-home__day">
      ((date | momentHomeDateText))
    </h5>
@@ -45,10 +45,8 @@
      </li>
    </ul>
  </template>
  <a class="more-link" href="/news-events/events/upcoming">href="/news-events/events/upcoming?eventType=Class/ Workshop">
    Calendar of EventsWorkshops &amp; Classes
    <i class="fa fa-angle-double-right"></i>
  </a>

</section>
```

Anyway, I'm not suggesting that we go ahead with this refactor right now prior to the launch, but I've created a [new issue for `v1.x`](https://github.com/cul-it/mann-wagon/issues/556). In the meantime there's an [additional issue for myself](https://github.com/cul-it/mann-wagon/issues/557) to address the broken layout.

**Comment by cappadona** [comment]
P.S. This new behavior is looking great :)

**Comment by tap87** [comment]
@cappadona Thanks for creating #556, I have been thinking about that for a while now and will tackle in the next version.
