### ISSUE TITLE
Fetch events for consistent number of days across all sources

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#517]
For initial call to data sources for events app, fetch all events for next 5 weeks.

* LibCal
* Localist
* R25

**Comment by tap87** [comment]
@cappadona I am thinking of using the site metafields to specify the number of days for requesting the data from the various data source.

**Comment by cappadona** [comment]
Sounds good. So you'll add a new namespace for events?

**Comment by tap87** [comment]
Yes, thanks.
