### ISSUE TITLE
Add id's to headings on hours page

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#518]
So that we can link to them from other pages.

We'll be doing so for the `consultation services`.

**Comment by eeh53** [comment]
@cappadona I added a note about the hours to the Consultation Services page at the very top. I was thinking that the "Hours page" text could be a link to the Consultation Area section of the hours page.

**Comment by cappadona** [comment]
@eeh53 Sounds good. Need a hand with the link?

**Comment by eeh53** [comment]
@cappadona Yeah, how do I get it to go directly to that part of the hours page? I want to do the same thing on the GIS Help Desk page.

**Comment by cappadona** [comment]
@eeh53 Just added an example for you, as described in [my comment above](https://github.com/cul-it/mann-wagon/issues/518#issuecomment-255423681).

**Comment by cappadona** [comment]
@eeh53 We all set here? If not, let me know how I can help.

**Comment by eeh53** [comment]
@cappadona Yes, I think so. I just did the exact same thing for the hours link on the GIS at Mann page.
