### ISSUE TITLE
Integrate hours onto hours page from LibCal API

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#53]
Hours to be shown by department (service point) for week. Current day is highlighted and future weeks can be shown by rotating week (carousel-like). https://issues.library.cornell.edu/browse/MANNWEB-235. Sub-task of https://issues.library.cornell.edu/browse/MANNWEB-133

**Comment by tap87** [comment]
The basic functionality for rendering the weekly hours has been created using a liquid drop in mann_liquid_extensions gem. We still need to create gem configuration file for the libcal api, and potentially the number of weeks (both are hardcoded right now).
In addition, we need to decide on how to display exceptions and create drop for rendering the exceptions as well.  I will create new issues based on all these comments
