### ISSUE TITLE
Disappearing content

### ISSUE THREAD

**Issue by sew268** [cul-it/mann-wagon#542]
Content disappears in the back office when clicking on a url on the right preview screen to go to another page to edit.  The page will appear in the preview screen but the content is lost in the editable square.

**Comment by cappadona** [comment]
My hope is that #538 will address this issue, at least dramatically reducing its frequency, but I've also learned not to underestimate the `sara` factor ;)

**Comment by cappadona** [comment]
Hopefully not jinxing it, but we've been good for over a month now after implementing #538. Feel free to revive if needed.
