### ISSUE TITLE
Update confirmation emails in LibCal for certain spaces

### ISSUE THREAD

**Issue by eeh53** [cul-it/mann-wagon#548]
Need to update confirmation emails for the following spaces to make them more consistent with other LibCal rooms (Mann 100, 102, Stone, Lobby):

- [x] One Button Studio
- [x] Interview Room
- [x] Collaborative Workstations
- [x] Group Room 282

**Comment by sew268** [comment]
@eeh53 take a look but I think this is now complete - I left it simple which I hope is ok
