### ISSUE TITLE
Use locomotive's path_to to dynamically set events-path

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#551]
Currently we have the events-path hardcoded (multiple times) in `homepage-template.html`. Ideally we would just pass the path to Vue via the `path_to` tag.

**Comment by tap87** [comment]
@cappadona What should the path_to value be, and is that going to change?

**Comment by cappadona** [comment]
Hey @tap87. Good question.

As you know, the [`path_to` tag expects the `page handle` as the first argument](https://locomotive-v3.readme.io/docs/tags#path_to). The events app is currently embedded on the upcoming-events (`/news-events/events/upcoming`) page and you can see that the handle is [currently set to `upcoming-events`](https://github.com/cul-it/mann-wagon/blob/dc66c18a057c851fb43460cc5c4cb6c5a0bb1274/app/views/pages/news-events/events/upcoming.liquid#L4).

Based on recent discussions around naming consistency for events and our decision to use **Calendar of Events** in #453 and #514, I'm recommending that we change the page handle for the upcoming-events page to: `events-calendar`.

Interested to hear what you think.

> The page handle is editable from the back-office, so there is a chance that this could be changed by a content editor down the road who doesn't understand the implications, but I that would be an easy fix when/if that happens.

**Comment by tap87** [comment]
@cappadona Does that change need to happen in the template or the backoffice. Also, does it make sense to use site metafields for the handle of the page.

**Comment by cappadona** [comment]
It can happen in the template or in the back-office, we just need to make sure that the two are synced up after the change. This is one of the pages we're already tracking in the repo and is exactly the kind of workflow issue I had in mind with [my comment from #529](https://github.com/cul-it/mann-wagon/issues/529#issuecomment-247369199).

I think it's overkill to use site metafields since the handle is now editable from the back-office. Let me know if you have any questions

**Comment by tap87** [comment]
I updated my comment about the metafield, instead of the handle it would be the path of the page. That way we don't need to worry about changing the template in the repo, just use the current path as default.

**Comment by cappadona** [comment]
There's a decent chance that the path of the page where the app is embedded will change before we launch. Locomotive already provides us with a way to dynamically get the path by passing the page's unique identifier to  `path_to`, so as long as we don't touch the `handle`, we should be good to go.

Yes, the handle can be edited from the back-office, where it's clearly labeled as a **unique identifer**:

![screenshot 2016-09-21 16 32 36](https://cloud.githubusercontent.com/assets/409842/18728053/80df524e-8019-11e6-8f33-d097ec3be4bc.png)


If we use the site metafield, then the content curators will manually need to keep that in sync with the path of the page where the events app is embedded. So in addition to moving the page in the back-office, they would also need to remember to edit this metafield. In my opinion there's more of a disconnect with this approach from the content editor's perspective...

**Comment by tap87** [comment]
I get your perspective, but I see some value in site metafields that if the path changes, we don't need to change the code to keep the two in sync.
There is another issue though, with using vue-router the [route maps](https://github.com/cul-it/mann-wagon/blob/dev/vue/events/events-page/events-page.js#L20) are also hardcoded and I can't access props in the vue instance, props work only inside a component. I could output a hidden div with data attribute in upcoming.liquid and grab that in Vue with plain old js.

**Comment by cappadona** [comment]
Thanks for pointing out the changes recently introduced with the move to `vue-router`. I didn't realize that we now have an additional instance of hardcoding the path to the page where the events app is embedded.

What about simply assigning a JS variable prior to initializing Vue? Something like this?

### Liquid snippet ( [`events-app.liquid`](https://github.com/cul-it/mann-wagon/blob/dev/app/views/snippets/events-app.liquid))
```liquid
...

<script type="text/javascript">
  var eventsPath = '{% path_to upcoming-events %}';
</script>

{{ 'eventsPage.bundle.js' | javascript_tag }}
```

### Vue entry ( [events-page.js`](https://github.com/cul-it/mann-wagon/blob/dev/vue/events/events-page/events-page.js#L20))
```js
...

var App = Vue.extend({})

router.map({
  eventsPath: {
    name: 'events',
    component: Events
  }
})

router.start(App, 'body')
```

Just to be clear, there will be no need to touch the JS code if the path changes, because Locomotive's `path_to` tag dynamically builds the path to the page using the page's unique ID (the `handle`).

**Comment by tap87** [comment]
Done in PR #564
