### ISSUE TITLE
Usability Tasks Round #4

### ISSUE THREAD

**Issue by sew268** [cul-it/mann-wagon#552]
1. Mann Library holds **Fabrication Fridays** each week.  Find the time and location for Fabrication Fridays. Then find any additional information about them as well.
2.  One of the student groups you belong to wants to hold a fundraiser and so you'll need to book a table in the Mann Library lobby.  Find the lobby and make a reservation for a time and date that works for you.
3.  You need to use MiniTab to complete your assignment.  Determine whether Mann has this software and if so, identify which computers have it installed.
4.  You need to borrow an item that is on reserve for COMM 3110. Find what items are on reserve and whether they are available to borrow right now.
5.  Your instructor told you that you need to make an appointment with Erica Johns, Mann Library's Research Data & Environmental Science Librarian. Find her contact information - how might you go about setting up a meeting with her.

**Comment by cappadona** [comment]
Thanks. Just edited the task list with some minor tweaks.

If we can provide details on what we have in mind for the News task, that would help answer whether it's feasible and also prioritize the work in that area.

**Comment by sew268** [comment]
Thanks!  Hmm, I guess we were thinking something fairly simple like find the news story about X.  But looking at all the news stories on our current site it's clear that the news is really geared more to faculty & staff and it isn't something that students would be searching.  Maybe this isn't the group to test this with??

**Comment by cappadona** [comment]
Yeah...students might not be the best audience for news, but if you want to flesh out that task I don't mind keeping it around as a potential for next week.

**Comment by sew268** [comment]
@cappadona Tobi & I have updated the tasks...see what you think!

**Comment by cappadona** [comment]
Looks good to me. Are we planning on setting up Erica with some availability in My Scheduler prior to tomorrow?

**Comment by sew268** [comment]
Yes - Tobi and will work with her on getting that set up.

Here's our student line-up for tomorrow (I'm sending them all reminders today):

1PM - Austin Morgan - CHE 2019
1:30PM - Matt will recruit
2:00PM - Kavin Lam - AEM 2018
2:30PM - Matt will recruit
3:00PM - Karly Krasnow - COMM 2018
