### ISSUE TITLE
New boolean field for spaces content type to indicate advanced reservation required

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#569]
This would cover both lobby tables and stone classroom. If true, don't check availability and render **Reservations required in advance** adjacent to the the reserve button.

**Comment by tap87** [comment]
Are we keeping the "Unavailable" text for these rooms?

**Comment by cappadona** [comment]
No, because if this boolean field is `true` then we don't even check availability, so we wouldn't know one way or the other and we'd have nothing to report ;)

**Comment by tap87** [comment]
Done via PR #586
