### ISSUE TITLE
Document workflows and requirements for room/space reservations

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#57]
https://issues.library.cornell.edu/browse/MANNWEB-241

**Comment by sew268** [comment]
![reservation workflow 2](https://cloud.githubusercontent.com/assets/14821406/12920668/87874d62-cf17-11e5-9d80-0dc51bd9b83b.jpg)
![reservation workflow](https://cloud.githubusercontent.com/assets/14821406/12920671/87978402-cf17-11e5-8dac-189e957a1a52.jpg)
![room bookings current workflow](https://cloud.githubusercontent.com/assets/14821406/12920673/87a28762-cf17-11e5-9687-19b801f427d4.jpg)
![workflow - 100 102](https://cloud.githubusercontent.com/assets/14821406/12920670/8793911c-cf17-11e5-9c9b-06314673b220.JPG)
![workflow - interview obs hive group study](https://cloud.githubusercontent.com/assets/14821406/12920669/879000c4-cf17-11e5-9e79-330d875e6c9a.JPG)
![workflow - lobby](https://cloud.githubusercontent.com/assets/14821406/12920672/879b8eee-cf17-11e5-94df-0db127be848c.JPG)
![workflow - stone classroom](https://cloud.githubusercontent.com/assets/14821406/12920674/87a3dd38-cf17-11e5-89f2-fe45cd572b7e.JPG)
