### ISSUE TITLE
Implement mega menu using {% nav %} tag

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#59]
> https://issues.library.cornell.edu/browse/MANNWEB-244

**Comment by cappadona** [comment]
Currently running into a bug when attempting to use the{{snippet}} option with the [nav tag|https://locomotive-v3.readme.io/docs/tags#nav] to control the rendered output of each item in the menu. Will be checking in with Didier to get this resolved.

```ruby
Arrrghhhh, we could not render page

undefined method `split' for #

File: ?

Code

No code

Back trace

/Users/nick/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/template.rb:237:in `tokenize'
/Users/nick/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/template.rb:124:in `parse'
/Users/nick/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/template.rb:110:in `parse'
/Users/nick/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc10/lib/locomotive/steam/liquid/tags/nav.rb:260:in `parse_snippet_template'
/Users/nick/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc10/lib/locomotive/steam/liquid/tags/nav.rb:233:in `set_template_if_asked'
/Users/nick/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc10/lib/locomotive/steam/liquid/tags/nav.rb:34:in `render'
.
.
.
```

> Jira comment from 2016-01-12

**Comment by tap87** [comment]
All the [rspec tests for nav tag](https://github.com/locomotivecms/steam/blob/master/spec/unit/liquid/tags/nav_spec.rb) were successful. I have been trying to debug the issue, but so far haven't found anything. I have reported the [issue](https://github.com/locomotivecms/steam/issues/59) in steam repo.

**Comment by tap87** [comment]
This bug has been [fixed](https://github.com/locomotivecms/steam/issues/59) in steam 1.0.1

**Comment by cappadona** [comment]
Thanks @tap87 (& @did). Now let's see if I can implement our mega menu.

**Comment by cappadona** [comment]
Removing this from March 2016 sprint and into the [push leading up to the April 2016 sprint](https://github.com/cul-it/mann-wagon/milestones/tween-marapr) based on our discussion at today's standup.

**Comment by cappadona** [comment]
All set and deployed to dev. Will need further tweaking once we build the site out further.
