### ISSUE TITLE
Add entries for R25 and CIT LabStats in reservation system content type

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#592]
And setup logic for reserve button for spaces cards. Both should open up the respective URLs in new tabs/windows

**Comment by cappadona** [comment]
Simplified the `reservation_systems` content type in 23a3a80 and added entries for the following (also assigned them to the appropriate spaces):
* LabStats (both CIT labs)
* R25 (B30 classrooms)

**Comment by eeh53** [comment]
Added note to notes field for these spaces to appear on individual space cards/space pages.

For basement classrooms (B30A and B30B): Reservations managed by CALS Registrar

For CIT classrooms (112 and 220A): Reservations managed by CIT
