### ISSUE TITLE
Create ruby gem for custom liquid drops to render hours from libcal api

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#61]
For the initial version of the gem, it would render the open/closed status of the library, and open until time on the homepage. https://issues.library.cornell.edu/browse/MANNWEB-249

**Comment by tap87** [comment]
A second version of the gem has been developed, which extends the functionality to render the weekly hours on the full hours page [Hours-Dev site](http://mannlib-dev.library.cornell.edu/hours)
