### ISSUE TITLE
Equipment availability

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#616]
- [ ] List availability of all equipment on `/use/technology/equipment`
- [ ] Availability within each sub-page (i.e. `/use/technology/equipment/cameras`)

Basically following the pattern in [current site](http://mannlib.cornell.edu/equipment-software/equipment-loans).

**Comment by tap87** [comment]
@cappadona, @eeh53 How closely are we following the equipment patterns on the current site. On the dev site, the child pages are not for specific equipment items as they are on the current site.

**Comment by cappadona** [comment]
Yeah, the dev site is organized a bit differently by introducing item grouping. So for example, `/use/technology/equipment/camera` would have the availability for both the [digtial SLRs](http://mannlib.cornell.edu/equipment-software/equipment-loans/digital-video-camera-0) and the [digital point-and-shoots](http://mannlib.cornell.edu/equipment-software/equipment-loans/digital-camera-0) from the current site.

That make sense?

**Comment by tap87** [comment]
Ok. Yes, I get it.
And is all the data (all equipment, and individual items) coming from the same mannservices endpoint?

**Comment by cappadona** [comment]
Yep...all the data is coming from [mannservices](http://mannservices.mannlib.cornell.edu/LibServices/secure/manageEquipment.do?locationId=14). Here are the callbacks from the Drupal module for the current site:
* [all equipment](https://github.com/cul-it/libassets/blob/master/libassets.module#L77)
* [equipment type](https://github.com/cul-it/libassets/blob/master/libassets.module#L87)

**Comment by tap87** [comment]
Deployed to dev

**Comment by sew268** [comment]
@tap87 this looks amazing!!  Really nice work.
