### ISSUE TITLE
Disable default date for events calendar datepicker

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#627]
Unfortunately, this is a longstanding bug with the jquery-ui widget and the [`defaultDate` option](http://api.jqueryui.com/datepicker/#option-defaultDate) when using it inline, but it looks like there are several possible [workarounds/hacks](http://stackoverflow.com/questions/3668325/jquery-datepicker-no-default-date).

**Comment by tap87** [comment]
Deployed to dev
