### ISSUE TITLE
Mann Staff

### ISSUE THREAD

**Issue by sew268** [cul-it/mann-wagon#629]
- [ ] Mann Staff - week of 10/10 - reminder that the launch is happening 10/25 along with some bullet points on what will be different, who to contact if they have issues, and a link to the dev site so they can familiarize themselves with the IA.  Also remind them that this is version 1.0 and that a good number of suggestions from our usability testing and staff demo are planned for future iterations.

**Comment by eeh53** [comment]
Dear Mann staff,

The new Mann website is scheduled to launch on Tuesday, October 25. Thank you to everyone who came to our show ‘n tell session in August to share feedback with the website development team, as well as those of you who participated in the staff user testing in July. This has truly been a group effort, so we also want to extend a special thanks to the other members of the website committee who have helped guide this effort: Michael Cook, Eveline Ferretti, Keith Jenkins, and Jim Morris-Knower.

One big change we want to make sure everyone is aware of is the change in reservation systems for Mann 100, 102, the lobby, and Stone Classroom. Reservations for these spaces will now be managed in LibCal, which is the system we currently use for many of our reservable study spaces (the Bissett workstations, Interview Room, and the One Button Studio). Mann 160 will now be managed in Outlook, and starting on October 25, you can reserve 160 from Outlook the same way you would book Mann 202A.

The website has been designed to provide a user-friendly experience. With improved navigation and functionality throughout, access to information about the library, our staff and resources, and our spaces has never been easier! Some other changes/improvements to look out for:

- “Available Now” section on the homepage which shows real-time availability of computers and study spaces 
- “Meet Our Experts” page that highlights Mann staff and their areas of expertise, as well as new functionality that enables users to book a consultation with the expert of their choice
- New and improved Events page featuring information about classes, workshops, and other events happening at Mann
- Organization & Staff page which features photographs and contact info for all Mann staff
- “Find a Space” page that features key info about our study spaces, classrooms, and conference/meeting rooms and allows users to easily reserve the room/space of their choice
- More detailed Hours page with hours information about our building, service desks, and other consulting services

Watch our current site the week of October 17th for an announcement, which will also include a link to the beta site and information on how you can provide feedback!


Sara E. Wright, on behalf of the website development team:
Darcy Branchini
Nick Cappadona
Tobi Hines
Tahir Poduska
