### ISSUE TITLE
Mann Web Committee

### ISSUE THREAD

**Issue by sew268** [cul-it/mann-wagon#630]
- [x] Mann Website Committee - week of 10/10 - one more meeting giving a review of the site IA and site content management plan discussion

**Comment by eeh53** [comment]
Agenda (feel free to edit/add):

1. Site overview and review changes since last round of usability testing
2. Discuss "Book a Consultation" feature and reminding librarians to fill out availability in My Scheduler asap
3. Develop content management strategy after launch

**Comment by eeh53** [comment]
Meet rescheduled for 10/26 @ 4:00 PM.

1. Site overview and review changes since last round of usability testing (book a consultation, meet our experts, events feed, reservations for 100, 102, Stone)
2. Discuss future development and priorities for v. 1.X
3. Content management stratetgy
