### ISSUE TITLE
Review Reservation Changes

### ISSUE THREAD

**Issue by sew268** [cul-it/mann-wagon#631]
- [x] Select Mann Staff - week of 10/10 & 10/17 - Brief overview of LibCal in small groups or one-on-one.  
- [x] Key Mann Reservations folks - week of 10/10 - more in-depth review with Sara or Tobi

**Comment by eeh53** [comment]
Select Mann Staff:
- [x] Meg
- [x] Mel
- [x] Noah
- [x] Wendy
- [x] Kat
- [x] Tom T.
- [x] Chris
- [x] Nancy
- [x] Lianna

**Comment by eeh53** [comment]
Key Mann Reservations Staff - Sara meeting with Matt and Jimmy 10/13
