### ISSUE TITLE
Communication to outside groups

### ISSUE THREAD

**Issue by sew268** [cul-it/mann-wagon#632]
- [x] Faculty & Staff - week of 10/10 - Mannifest news story 

- [x] Students, Faculty & Staff - week of 10/17 - web banner at the top of current site with a link to dev site

- [x] All CUL - 10/25 - email the day the site launches sent by Mary crafted by us

**Comment by eeh53** [comment]
Mannifest news story:

Mann Library will be launching a new website on October 25th which has been designed to provide a user-friendly experience. With improved navigation and functionality throughout, access to information about the library, librarians, resources, and spaces has never been easier. Watch our current site the week of October 17th for an announcement, which will include a link to the development site and information on how you can provide feedback!

**Comment by sew268** [comment]
All CUL email:

Dear CUL,

You may have noticed that our website looks very different as of today!  Our new site has been reworked from the ground up, incorporating an iterative, user-centered design to provide an optimal user experience for both our patrons and staff. With improved navigation and functionality throughout, access to information about the library, our staff and resources, and our spaces has never been easier! 
Some changes/improvements of particular note:
•	Available Now section on the homepage which shows real-time availability of computers and study spaces
•	Meet Our Experts page that highlights Mann staff and their areas of expertise, as well as new functionality that enables users to book a consultation with the expert of their choice
•	New and improved Events Calendar featuring information about classes, workshops, and other events happening at Mann
•	Divisions & Staff page which features photographs and contact info for all Mann staff
•	Space Finder that features key info about our study spaces, classrooms, and conference/meeting rooms and allows users to easily reserve the room/space of their choice
•	More detailed Hours page with hours information about our building, service desks, and other consulting services

I’d like to thank the development team – Nick Cappadona, Tobi Hines, Darcy Branchini, Tahir Paduska, and Sara E. Wright -  for all the time and hard work that they put into creating this site and the rest of the Mann website committee – Jim Morris-Knower, Keith Jenkins, Eveline Ferretti, and Michael Cook – who helped to shape its direction. 
We welcome your feedback as we continue to implement new features and ideas.  Please fill out our site feedback form or contact anyone on the development team directly.  

Enjoy!
Mary Ochs

**Comment by sew268** [comment]
bummer - I made a lot of that text links; that's the plan anyhow
