### ISSUE TITLE
Update Consultation Services listed on Hours page

### ISSUE THREAD

**Issue by eeh53** [cul-it/mann-wagon#644]
Need to add "Knight Graduate Writing Service" (already in LibCal) to hours page

**Comment by tap87** [comment]
Deployed to dev. @eeh53 @sew268 The table reflects how the entries are ordered in LibCal, you can change the order of how they appear in LibCal, and on other places that use the LibCal widget, (CUL hours, etc.)

**Comment by sew268** [comment]
I'll update the order so that they're alphabetical
