### ISSUE TITLE
Cache LibCal API response for hours

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#656]
@tap87 If you're interested, take a look at cul-it/circ-display#17 to see how I implemented this for the consultation display.

**Comment by tap87** [comment]
@cappadona Should the hours response be cache for 2 minutes as well?

**Comment by cappadona** [comment]
That's what we settled on for the digital signage. Our thinking was that it's a good compromise between the minimum requested by Springshare (1 minute) and keeping the number of requests as low as possible while still allowing us to get changes to our hours reflected within a reasonable timeframe.

Interested to hear your take on it.

**Comment by tap87** [comment]
I agree, sounds like a good compromise.
