### ISSUE TITLE
Link event location to SmartMap for events & events-home

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#665]
Make use of the `smartmap_url` field which has been populated for all existing curated locations. See #611.

> The location would be a link only in the event listing, not when used as a label for filters

<img width="674" alt="screenshot 2016-10-13 09 36 08" src="https://cloud.githubusercontent.com/assets/409842/19351183/b9950992-9128-11e6-9433-92383756f074.png">

**Comment by tap87** [comment]
Deployed to dev. Links open in a new tab, to maintain the state of events app

**Comment by cappadona** [comment]
I'm not seeing these just yet on the dev site...but it sounds great ;)

**Comment by tap87** [comment]
You should see it now.
