### ISSUE TITLE
Update events calendar to filter out LibCal events marked as duplicate

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#666]
Test for `Additional Notes` field contains `duplicate-mann`. We will never render this field on our site.

**Comment by cappadona** [comment]
@tap87, Sara just added two duplicate events as test data in #664.

**Comment by tap87** [comment]
Deployed to dev

**Comment by cappadona** [comment]
This needs to be re-implemented. Context in #443. Let me know if you have any questions.

**Comment by tap87** [comment]
Done and deployed to dev again.
