### ISSUE TITLE
Remove "page content here" from forms

### ISSUE THREAD

**Issue by sew268** [cul-it/mann-wagon#668]
Currently we have placeholder text defined in the inherited layout (`basic_page`) for the editable_element in question. The expected behavior is that any page which inherits this layout can override the placeholder text, including an empty string, but there was a bug in Steam which was preventing this. I believe it's been addressed upstream, but I'll need to verify that.

**Comment by sew268** [comment]
@cappadona you may know this already but landing pages for mega menu categories have the note 'Brief description here'.

**Comment by cappadona** [comment]
Yep...the resolution to this issue will address placeholder text for all `editable_text` across the site. Thanks :)

**Comment by cappadona** [comment]
All set.
