### ISSUE TITLE
Toggling between 2 values in the date filter can lead to unexpected results

### ISSUE THREAD

**Issue by sew268** [cul-it/mann-wagon#671]
tried to toggle between 10/25 and 10/27 on the calendar and when the 10/25 filter was being applied, the events listed were for 10/27
![events](https://cloud.githubusercontent.com/assets/14821406/19365935/0cb37c28-9163-11e6-9862-dbb6dca282c7.PNG)

**Comment by tap87** [comment]
@sew268 Thanks for reporting this issue. If the dates are clicked before the data is returned, then the wrong data might be displayed, depending on which date request gets processed first. I will work on cancelling a previous request in this case.

**Comment by tap87** [comment]
Deployed to dev.

**Comment by tap87** [comment]
Reopening since libcal reservation calls via mannservices weren't addressed as part of the fix.

**Comment by tap87** [comment]
Deployed to dev
