### ISSUE TITLE
Any chance we can provide a direct link to the edit page within LibCal admin to help staff mark duplicates?

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#672]

**Comment by tap87** [comment]
Unfortunately not. These are all Post requests, and won't work in if directly used in the browser.

**Comment by cappadona** [comment]
Thanks for looking into, Tahir. Reviving this for @sew268 to see if she can make any headway by contacting Springshare directly.

**Comment by sew268** [comment]
Email sent - we'll see how they respond
