### ISSUE TITLE
Problem with default number of days (35?) for Events Calendar

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#673]
As of earlier this week, we noticed the scenario where the *Events/Exhibits* on the homepage was empty. This is surprising since the default number of days to query for two of the three sources is 35 days.

Today is `10/13` and here are two `Author Appearances` in the next 35 days:
 * [A Sea of Glass](http://events.cornell.edu/calendar/month/2016/10?event_types%5B%5D=4228&event_types%5B%5D=4250) - `10/27`

* [Emotion, Aging, and Health](http://events.cornell.edu/calendar/month/2016/11?event_types%5B%5D=4228&event_types%5B%5D=4250) - `11/9`

**Comment by tap87** [comment]
Some events in localist don't have an event end time, and these were getting filtered out from the initial load along with the events that have already passed.

**Comment by tap87** [comment]
Deployed to dev

**Comment by cappadona** [comment]
Thanks for getting to the bottom of this. Just so everyone's on the same page, for any event from Localist that only has a start time (appears to be a CUL convention for Author Appearances), it will remain on the calendar until the end of the day it's scheduled.
