### ISSUE TITLE
Fines & Billing is stranded!

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#69]
Now that @eeh53 changed the parent page ([Borrow, Request, Renew](http://mannlib-dev.library.cornell.edu/services-support/borrow-request-renew)) to a redirect to the CUL site, there's no easy way to get to this sub-page:

http://mannlib-dev.library.cornell.edu/services-support/borrow-request-renew/fines-billing

**Comment by sew268** [comment]
Changed the status of the Borrow, Renew, Request page so that it no longer redirects to CUL's.  The hope was then to add some brief content with links to CUL's site so that 'fine & billing' isn't stranded.  However, there appears to be a bug because it isn't letting us save new content and instead show the content of the page as that of CUL's.

**Comment by cappadona** [comment]
@sew268 Very interesting. I was able to reproduce this and then got around it by:

1. Toggling the redirect back on
1. Deleting the URL in the redirect field
1. Toggling the redirect off
1. Saving

If this behavior still exists after updating to the latest, I'll submit a bug report.

**Comment by sew268** [comment]
Thanks and sounds like a plan!

**Comment by eeh53** [comment]
@cappadona It looks like this issue is still there. Just tried turning off the redirect for Current Awareness page without deleting the url, and the CUL webpage content was still showing.

**Comment by eeh53** [comment]
We decided to put Borrow, Request, Renew, Borrow Direct & Interlibrary Loan, My Account, and Fees and Billing all on the same page (Borrow, Request, Renew). It is no longer a redirect, but has links to the CUL pages with the correct content. Stranding problem solved.

**Comment by cappadona** [comment]
@eeh53 Thanks, I'm able to reproduce this locally as well. Will submit a bug report for the Locomotive team.
