### ISSUE TITLE
Banner on current site announcing launch with link to dev site

### ISSUE THREAD

**Issue by sew268** [cul-it/mann-wagon#690]
* ~~Cleanup site content for consistency~~ #444
* ~~Add contact info on home page for librarians~~ #601
* ~~Remove hardcoded desktop availability from spaces cards~~ #645
* ~~Remove placeholder text for editable elements~~ #668
* ~~Remove libcal reservations for conference rooms, classrooms, and lobby~~ #692
* ~~Dismissable banner at top of dev site with a link to site feedback~~ #693
* ~~Update spotlight feature so that slides are current~~ #694
* ~~Link *Chat with a Librarian* in the footer~~ #695

**Comment by cappadona** [comment]
Closing as `wontfix` in favor of a [milestone](https://github.com/cul-it/mann-wagon#boards?milestones=Beta%20launch#2016-10-18&notFullScreen=false&repos=42308823,38134030,48058024&showPRs=false). This will be easier to track/manage.
