### ISSUE TITLE
Fix uncurated filters in events

### ISSUE THREAD

**Issue by tap87** [cul-it/mann-wagon#714]
Certain event filters, both room names and event types still show as uncurated even when added to curated in the back office

**Comment by tap87** [comment]
@cappadona @sew268 This issue was caused by couple of bugs in the code:

1.  r25 event types were hardcoded to 'Class/Workshop'.
2. Leading and Trailing white spaces were not trimmed from the incoming events.

Now, r25 events are handled the same way. I was able to find a field that would work for event type. You should see 'Instruction' event type that needs to be curated.

**Comment by tap87** [comment]
Deployed to dev.

**Comment by cappadona** [comment]
@tap87, not hardcoding the event type for R25 sounds great. I'm not yet seeing the uncurated `Instruction` event type in dev.

**Comment by tap87** [comment]
@cappadona You beat me to it. I added it to back office, but will remove that now. Just saw #717
