### ISSUE TITLE
Dynamic filtering logic for homepage events

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#718]
Currently the type value is hardcoded, looking for `Class/Workshop` but since we've provided content editors with the ability to manage event types via back-office, it would be ideal to also allow them to indicate which type should be used for this filtering.

> If that's too much to ask for at the moment, a quick initial implementation would be to hardcode it to a new value of `Workshop/Class` ;) 

This is the result of conversations around #717.

**Comment by tap87** [comment]
Hardcoded the values for beta launch. And deployed to dev.

**Comment by tahirpoduska** [comment]
Done and deployed to dev and production. By default uses "Workshop/Class" if not set in back office.
