### ISSUE TITLE
Enable R25 production feed with improved handling

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#720]
Bring R25 data back into the fold and implement a toggle on the Events Calendar (essentially a new filter), separate from the events type, that defaults to false.

I'll add a quick mockup of this after the dust settles to better convey what we have in mind. 

> See #717, #718, #719 for context and background

**Comment by cappadona** [comment]
@tap87  I've created PR #747 as a start for this effort. which includes an initial commit that introduces the non-functional toggle seen below. Please let me know if you have any questions.

<img width="1153" alt="screenshot 2016-10-21 11 13 55" src="https://cloud.githubusercontent.com/assets/409842/19603531/8142a8a8-977f-11e6-98c8-e2e567d6726c.png">

**Comment by tap87** [comment]
Deployed to dev
