### ISSUE TITLE
Add Mary's signature to 'About Us' page

### ISSUE THREAD

**Issue by sew268** [cul-it/mann-wagon#727]

**Comment by sew268** [comment]
@cappadona new content and photo added to 'About Us' page - all it needs now is the signature :)

**Comment by cappadona** [comment]
@sew268 Thanks. Do we want the *MannYoufacture* link to open in a new tab/window?

**Comment by sew268** [comment]
@cappadona That would be great!

**Comment by cappadona** [comment]
That's all you, but let me know if you need a hand ;)

Also, I just quickly removed the background from Mary's sig on our current site so we have something for the time being. I still plan on getting a new hi-res version later this week.
