### ISSUE TITLE
Hive(282) hours displaying as 'Open until 12 am' instead of 'Open until Midnight'

### ISSUE THREAD

**Issue by tap87** [cul-it/mann-wagon#737]

**Comment by tap87** [comment]
Deployed to dev

**Comment by cappadona** [comment]
Thanks Tahir...this is just a what-if scenario, correct? The interview room follows basement hours which I believe never close later than 10pm.

**Comment by tap87** [comment]
Sorry, it was for the hive, I updated the title.
