### ISSUE TITLE
Reservation form for Mann 100, 102

### ISSUE THREAD

**Issue by eeh53** [cul-it/mann-wagon#74]
**Reservation Booking Form**
- [ ] Name 
- [ ] Email
- [ ] Phone number
- [ ] Dept. account number
- [ ] College
- [ ] Department
- [ ] Department Account # (enter N/A if not applicable)
- [ ] Event Name
- [ ] Event Description

Confirmation email should include info about key being available at circ desk; how to request tech support; if ‘advertise on library kiosk’ selected, confirmation email should include link to instructions on submitting slide

[Existing form on current site](http://mannlib.cornell.edu/rooms-labs/seminar-conference-rooms/reservation-request)

**Comment by tap87** [comment]
@sara @tobi I know we are thinking about a new workflow for reservations, but based on the current site with separate cards for each room do we still need a select room (100,102).

**Comment by eeh53** [comment]
@tap87 If it's possible, I think we would still like to have the room selection on the form, in case someone has chosen the wrong room by accident and needs to select the other one, and that way they don't need to exit out of the form and return to the spaces page. However, maybe the form could pre-select whatever room it is that they initially selected. So, for example, if they navigated to the reservation form because they selected Mann 102, "Mann 102" would be pre-selected. Does that make sense?

**Comment by tap87** [comment]
@eeh53 Maybe we can start with the basic version without the select list, just an idea. Also, how does this issue relate to the workflow created in #12?

**Comment by eeh53** [comment]
@tap87 Sure, if it's going to be an issue to have the select list, we can start without it. As far as the workflow created in #12, it has changed a bit since we've redone the spaces pages. Now users will be making reservations straight from the "cards" view. I think we would like to have a calendar view with available times listed (similar to functionality of the LibCal My Scheduler widget), but I think we were going to hold off on this for the user testing we have scheduled for next Thursday, 7/28 and just focus on the reservation form for now.

**Comment by tap87** [comment]
If having a calendar view with available times listed is a requirement, then I think we should develop that feature and then do user testing. It is a different workflow from what I am trying to build now.

**Comment by eeh53** [comment]
I guess it is an additional step in that process - before you get to fill out the form with all your info, you need to select your day and time. That is how we anticipate users will want it to function. I think in our meeting the other day, we thought that perhaps it would be better to just proceed with the reservation form without that calendar view and see how users respond, i.e. do they really want that calendar view of availability?

**Comment by cappadona** [comment]
Ended up using LibCal for this form.
