### ISSUE TITLE
Debug consume tag with header_auth and expires_in options

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#745]
See #744 for details.

**Comment by tap87** [comment]
@cappadona Just created PR #770, had to move the templates inside the consume tag to use the cache. Let me know if you have any questions.

**Comment by cappadona** [comment]
@tap87 I finally got a chance to review this...sorry for the delay. Unfortunately I was unable to get it to run when the site is served by Engine. It's the same issue as before where it appears the consume tag is ignored (or fails silently) when both the `header_auth` and `expires_in` options are present.

Are you not able to reproduce this behavior? We can discuss it further tomorrow, but for now, we should keep this out of the launch.

**Comment by tap87** [comment]
@cappadona I was able to get the consume tag work as expected on my local engine with both the options present.

**Comment by tahirpoduska** [comment]
Deployed to production
