### ISSUE TITLE
Reservation form info for lobby

### ISSUE THREAD

**Issue by eeh53** [cul-it/mann-wagon#75]
**Reservation Booking Form**
- [ ] Name 
- [ ] Email
- [ ] Phone number
- [ ] Dept. account number
- [ ] College
- [ ] Department
- [ ] Department Account # (enter N/A if not applicable)
- [ ] Event Name
- [ ] Event Description

Confirmation email should include info about asking for tables at circ desk; info on how to ‘advertise on library kiosk’ selected, possibly a Walls My Scheduler.  

[Existing form on current site](http://mannlib.cornell.edu/rooms-labs/seminar-conference-rooms/lobby-event-reservation-request)

**Comment by cappadona** [comment]
Ended up using LibCal for this form.
