### ISSUE TITLE
Reservation form info for Stone Classroom

### ISSUE THREAD

**Issue by eeh53** [cul-it/mann-wagon#76]
**Reservation Booking Form**
- [ ] Name 
- [ ] Email
- [ ] Phone number
- [ ] Dept. account number
- [ ] College
- [ ] Department
- [ ] Department Account # (enter N/A if not applicable)
- [ ] Event Name
- [ ] Event Description

Confirmation email should include info on how to request tech support.

[Existing form on current site](http://mannlib.cornell.edu/rooms-labs/classrooms-labs/reservation-request)

**Comment by cappadona** [comment]
Ended up using LibCal for this form.
