### ISSUE TITLE
https config

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#768]
- [x] Mixed content for LibCal modal (i.e. [Stone Classroom](https://mannlib.cornell.edu/use/spaces/all/stone-classroom))

**Comment by cappadona** [comment]
I've implemented a temporary fix in #803 (nix the modal -- open in a new window/tab), but not checking off LibCal modal from the list. Once the issue with the SSL cert for `spaces.library.cornell.edu` is resolved, we'll want to revert fb66fd9.

**Comment by cappadona** [comment]
Springshare introduced [support for SSL cert on custom domains in December](http://blog.springshare.com/2016/12/05/libguides-v2-server-move-and-many-new-features/). Alan will fill out the form and we should be on our way.

**Comment by amccarty** [comment]
Created a springshare support ticket (#112081) since I haven't heard from anyone on their end since filling out the beta SSL request form.

**Comment by cappadona** [comment]
We heard back from Springshare support. SSL is currently only offered for LibGuides, but Alan reached out to our developer contact and they're working on supporting SSL on `spaces.library.cornell.edu` (our LibCal domain) as early as next week.

Bumping to April milestone for now.

**Comment by cappadona** [comment]
We now have a valid cert for spaces.library.cornell.edu thanks to Alan and Anthony and the modal for any/all LibCal space reservation has returned to dev.

**Comment by cappadona** [comment]
Deployed to prod.
