### ISSUE TITLE
Reservation form info for Bissett/One Button Studio/Interview Room/Group Rooms

### ISSUE THREAD

**Issue by eeh53** [cul-it/mann-wagon#77]
**Contact info (private)**
- [ ] Name
- [ ] Email

**Reservation info (public)**
- [ ] Group name
- [ ] How many people in your group? (Bissett/Group Rooms)
- [ ] Date/time edit

**Other info (private)**
- [ ] Tech support needed? (Bissett/One Button Studio/Interview Room)
- [ ] Is this for a course project? (yes/no, free-text box to capture info if "yes" selected)

If ‘tech support’ selected, notification email sent to appropriate staff member

**Comment by cappadona** [comment]
Using LibCal widget #220, so this is no longer necessary.
