### ISSUE TITLE
Evaluate Booked

### ISSUE THREAD

**Issue by sew268** [cul-it/mann-wagon#81]
Next logical step after work on issue #48 
Can begin once #72 is done

**Comment by cappadona** [comment]
[Booked instance](http://booked-dev.library.cornell.edu) is ready to go.

**Comment by sew268** [comment]
Booked has a lot possibility; seems to have a lot of the features that we're looking for.  A road block for us has been the terminology that Booked uses and trying to understand all the different parts and how they would integrate.  Nick has alluded to a new release that isn't public yet but that is more modern and might address some of our difficulties.  Booked would take some customization but we think this might be worth a deeper investigation by Nick & Tahir to see how easy it would be to work with Booked and how easy it would be to have Booked talk to LibCal for hours integration.

**Comment by sew268** [comment]
Updated [requirements list](https://docs.google.com/spreadsheets/d/1nq5zXXHC8r1XTVfODcq-PAs4jWFizWacZP2CLhcogPw/edit#gid=942321703) to reflect priority order and separated requirements into what we would need inplace before going live and what could wait.  
@cappadona requirement T on the list is at the bottom of our needs to be in place list simply because we don't know what it's talking about. :)  Feel free to move it up to where you think it should be.

**Comment by cappadona** [comment]
thanks @sew268. I just updated the description for requirement T...that help? ;)

**Comment by sew268** [comment]
@cappadona - yes, that helps.
