### ISSUE TITLE
Evaluate MRBS

### ISSUE THREAD

**Issue by sew268** [cul-it/mann-wagon#82]
Related to #48 and can begin once #73 is done

**Comment by cappadona** [comment]
[MRBS instance](http://mrbs-dev.library.cornell.edu) is ready to go.

**Comment by sew268** [comment]
MRBS looks like it has a lot of the same features and annoyances that we've had.  Seems like it would require a lot of customization to be able to use it as we'd like.  Doesn't seem like there have been many updates to it so we wonder if it would be worth the time to customize it.  Hours integration is a big question - MRBS works for us now because of the web form that pings the hours service to know black dates/times and library closures as well as limiting how far in advance a reservation can be made.  Don't know how this would integrate with LibCal.

**Comment by sew268** [comment]
@cappadona we've updated the reservation requirements form; take a look and see if you can answer any of our questions or have any info to add
https://docs.google.com/spreadsheets/d/1nq5zXXHC8r1XTVfODcq-PAs4jWFizWacZP2CLhcogPw/edit

**Comment by cappadona** [comment]
@sew268 @eeh53 I've just reviewed the matrix and added comments. Let me know if I missed anything.

**Comment by cappadona** [comment]
MRBS is out.
