### ISSUE TITLE
Email links not working on Meet Our Experts page

### ISSUE THREAD

**Issue by eeh53** [cul-it/mann-wagon#821]
One of the faculty members from the Mann Library Committee reported this issue. On the Divisions & Staff page, clicking the email link at least takes you to the staff directory (though I think we are eventually planning on having this open a new email window). However, on the Meet Our Experts page, it doesn't do anything. I tried it in a couple different browsers (Chrome and Firefox).

**Comment by cappadona** [comment]
Across the board, use `mailto` for staff email links.

**Comment by cappadona** [comment]
Deployed to dev.

**Comment by cappadona** [comment]
Deployed to prod.
