### ISSUE TITLE
Add GIS Help Desk My Scheduler team to GIS webpage

### ISSUE THREAD

**Issue by eeh53** [cul-it/mann-wagon#824]
Keith would like there to be an option on the [GIS page](https://mannlib.cornell.edu/help/research-support/research-help/gis-at-mann) to schedule an appointment with any member of the GIS Help Desk support team: Keith, Noah Hamm, and Jeff Piestrak (instead of only giving the option to book with him). 

I have activated Jeff P's account in LibCal's My Scheduler and added a new My Scheduler group called "GIS Help Desk" that includes Keith, Noah, and Jeff.

**Comment by cappadona** [comment]
Deployed to dev.

**Comment by cappadona** [comment]
Deployed to prod.
