### ISSUE TITLE
Address iCal to JSON conversion issue in LibServices

### ISSUE THREAD

**Issue by tahirpoduska** [cul-it/mann-wagon#826]
Currently we are using iCal feed from libcal room bookings and converting it to JSON using LibServices. Sometimes, the conversion isn't successful and for now the code loops until it is successful and logs the fault in console, sometimes taking a long time.
We have a few options for dealing with this issue.

1. Parse the iCal feed in a ruby gem (mann_liquid_extensions)
2. Use a iCal to JSON JS library in the vue app
3. Wait till we migrate to the new equipment and room bookings (provides both read and write api)

**Comment by cappadona** [comment]
I vote for `#3`
