### ISSUE TITLE
Compress JS and CSS

### ISSUE THREAD

**Issue by tahirpoduska** [cul-it/mann-wagon#838]
I am planning on using webpack plugins to compress [css](https://github.com/NMFR/optimize-css-assets-webpack-plugin) and [js](https://github.com/webpack-contrib/uglifyjs-webpack-plugin)

**Comment by cappadona** [comment]
### Performance measured via Chrome DevTools Network panel
> Percentage of decrease from [baseline data](https://github.com/cul-it/mann-wagon/issues/831) in bold

| Environment | `DOMContentLoaded` | Load |
| --- | --- | --- |
| wagon | 24.78s (**49.8%**) | 43.81s (**11.2%**) |
| local engine | 27.25s (**53%**) | 56.63s (**3.1%**) |
| dev engine | 24.41s (**51.4%**) | 53.53s (**6.1%**) |

> Browser cache disabled and throttled to DSL (5ms, 2.0Mb/s, 1.0Mb/s)
>
> **PLEASE NOTE:** Averages of 3 data points. Total Payload was 15.2MB. Wagon had fewer (and different) spotlight images due to logic diff btw wagon and engine which resulted in smaller payload and faster load times.

**Comment by cappadona** [comment]
Deployed to dev and prod.
