### ISSUE TITLE
Disable CU Events advertising field in LibCal custom form

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#857]
All existing upcoming reservations should be reviewed soon after this change is put in place. See #858.

**Comment by eeh53** [comment]
@cappadona If we disable this field on the LibCal reservation form, are we good to go with the solution for de-duping outlined in issue #860?

**Comment by cappadona** [comment]
@eeh53 Does that mean the decision has been made? If so, this would just be the start of the cascade...lots of other effort around this would need to happen to make de-duping approach from #834 a reality

**Comment by eeh53** [comment]
@cappadona I think if that solution will work, then we're fine with getting rid of this field on the reservation form. We did talk about adding a "mark this event as private" field, but not sure where we left off on that decision.

**Comment by cappadona** [comment]
@eeh53 Yeah, we did discuss the *mark this event as private* option a while back but I don't remember a final decision being made. I think you and @sew268 wanted to discuss it further amongst yourselves.

My vote is to take care of this issue and #858 ASAP, while decisions are being made, to stop the bleeding. This will lead to duplication in the calendar, but in my opinion that's better than the current situation where we're missing events.

**Comment by cappadona** [comment]
Ended up not having to disable the field temporarily since I got the custom CSS in place from #860.
