### ISSUE TITLE
Drop CIT Lab 112 from desktop availability

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#876]
@eeh53 and/or @sew268 -- will you confirm that I've got this straight before I proceed?

> Basing this decision off of cul-it/mann-sitefeedback#47

**Comment by eeh53** [comment]
@cappadona Confirmed!

**Comment by cappadona** [comment]
Deployed to dev & prod

**Comment by cappadona** [comment]
Deployed to dev & prod
