### ISSUE TITLE
Suppress Equipment Calendar Test from monthly hours view?

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#879]
@eeh53 @sew268 I noticed earlier this week that we have a new guest on the [monthly hours view](http://mannlib.cornell.edu/hours).

Is this just temporary testing from @jpm287 and if so, for how long?

**Comment by jpm287** [comment]
I created that calendar with the intent of it serving as the base for our special equipment reservations module. It originally was a test, but it solved some of the reservation/scheduling issues I was struggling to fix. If we end up keeping it, we'd probably want to suppress it from the Mann calendar, however. @eeh53, @tit1, and I should hopefully be shaping out the rest of the equipment reservation stuff in the next few weeks!

**Comment by cappadona** [comment]
Thanks @jpm287. Will you post an update here once you have the equipment reservation plans finalized so we can make a decision on how to proceed?

**Comment by jpm287** [comment]
Definitely - will do!

**Comment by cappadona** [comment]
Hey @jpm287...any updates?

**Comment by jpm287** [comment]
Hiya @cappadona! @eeh53, @tit1, and I decided at our last meeting that we'll use the existing Plotter Calendar for the equipment hours. I think we don't need this test calendar anymore and that it served its purpose.

**Comment by cappadona** [comment]
Thanks @jpm287. Meant to update this issue since Tobi already went ahead and dropped the **Equipment Calendar Test** from LibCal yesterday 😄
