### ISSUE TITLE
Use projects as test case for content types

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#89]

**Comment by tap87** [comment]
@cappadona I have created [project content-type branch](https://github.com/cul-it/mann-wagon/tree/project-content-type) and pushed that to a [new site](http://mannloco-dev.library.cornell.edu/locomotive/inquisitive-volcano-8732/dashboard) in engine, with the [preview here](http://mannloco-dev.library.cornell.edu/locomotive/inquisitive-volcano-8732/preview). We need to figure out how to handle Featured Projects page and Projects page. The name of the content type and the page should match for the navigation and breadcrumbs to work properly.

**Comment by tap87** [comment]
See #90 and #91

**Comment by tap87** [comment]
See PR #96
