### ISSUE TITLE
Add new gallery spaces 

### ISSUE THREAD

**Issue by eeh53** [cul-it/mann-wagon#900]

**Comment by eeh53** [comment]
I tried to create a space for the Top Shelf Gallery, and when I clicked the "Create" button, I got an error message that said "Entry was not created." Not sure why this isn't working.

**Comment by cappadona** [comment]
Thanks...I was just able to create a space without any errors. Maybe you can provide the values you used for each field so I can help debug?

<img width="791" alt="screen shot 2017-11-27 at 4 15 34 pm" src="https://user-images.githubusercontent.com/409842/33289685-56a227b2-d38e-11e7-8498-4e940fd43ab7.png">

<img width="813" alt="screen shot 2017-11-27 at 4 15 51 pm" src="https://user-images.githubusercontent.com/409842/33289689-5b7efdf0-d38e-11e7-97b1-c8e6c160aa8c.png">

**Comment by eeh53** [comment]
@cappadona Cool, so that means I'm definitely doing something wrong. Sigh. 

Here are the fields I filled out:

1. Name - Top Shelf Gallery
2. Floor - First Floor
3. Types - Gallery & Exhibit Spaces
4. Description - The Mann Top Shelf Gallery is dedicated to showcasing and celebrating the work of Cornell's CALS and CHE faculty, researchers, organizations, and students. We also welcome collaboration with other institutions, as well as the Cornell and Ithaca communities at large. To inquire about working with us to develop an exhibit in the Top Shelf Gallery, please send us an email at mann-gallery-l@cornell.edu 
5. Photo - Select among assets, "Top Shelf Gallery" jpg

That's it! Now that I'm looking at the test one you created, I'm wondering if the issue is with the image.

**Comment by cappadona** [comment]
Thanks...I got the same behavior when using only the fields you specified above.

The issue is that the capacity **is required**. Unfortunately the app and browser doesn't do a good job of indicating this appropriately. So all I did to resolve this was set a value for capacity (I chose **N/A**).

https://mannlib.cornell.edu/use/spaces/gallery-exhibit

**Comment by eeh53** [comment]
Thanks for clearing that up!

**Comment by cappadona** [comment]
@eeh53 baked?

**Comment by cappadona** [comment]
greenlight from @eeh53 to remove from the oven for cooling
