### ISSUE TITLE
Prototype equipment page integrating loanable & reservable items

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#911]
Loanable items managed in Locomotive back-office. Reservable items managed in LibCal's S&E module and all info would be consumed/parsed via API.

### DSLR Cameras
* Canon TI5
* Canon TI5
* Canon TI5
* Canon TI5

### Videocameras
* Sony CX440
* Sony CX440
* Sony CX440
* Sony CX440

### Audio Recorders
* Zoom H1
* Zoom H1
* Zoom H1

### Microphones
* Blue Yeti

### Tripods
* Tripod 1
* Tripod 2
* Tripod 3
* Tripod 4
* Tripod 5

### Projector
* Epson VX240

### DSLR Cameras
* Canon TI5
* Canon TI5
* Canon TI5
* Canon TI5
 
### Videocameras
* Sony CX440
* Sony CX440
* Sony CX440
* Sony CX440
 
### Audio Recorders
* Zoom H1
* Zoom H1
* Zoom H1

### Microphones
* Blue Yeti

### iPhone Mic
* Zoom iQ7

### Tripods
* Tripod 1
* Tripod 2
* Tripod 3
* Tripod 4
* Tripod 5

### Projector
* Epson VX240

### GPS Units
* Garmin eTrex 30
* Garmin eTrex 30

### Thermal Imager
* Flir C2

**Comment by eeh53** [comment]
Reviewed on 9/20/17 with @jpm287 and this list looks good to us!

**Comment by cappadona** [comment]
@eeh53 Thanks for the confirmation!

**Comment by cappadona** [comment]
@jpm287 Just a friendly reminder to check in with @eeh53 re: status of `GPS Data Logger`. Staying in the loanable rotation or not?

**Comment by cappadona** [comment]
@cul-it/mann-website What does everyone think about combining **Microphones** & **iPhone Mic** under loanable equipment?
