### ISSUE TITLE
Option to search Mann Library, should contain results from Mann Library Website

### ISSUE THREAD

**Issue by tap87** [cul-it/mann-wagon#92]
Use the Google Custom search for this option, refer to #33 for more information and links

**Comment by tap87** [comment]
Locomotive CMS doesn't have search capability yet, but is up next in the [development](https://trello.com/b/kRiy1dZu/locomotive)

**Comment by tap87** [comment]
It seems like the search functionality should be available in the next release, but didn't get a timeline for that.

**Comment by cappadona** [comment]
Do you know whether he's referring to a major (`4.0`) or minor (`3.x`) release? Would be good to have some sense of a timeline. Just saw you're email, thanks for forwarding.

**Comment by tap87** [comment]
More chat with didier:

tap87 10:59
Hi @did.
It seems like the trello card we were talking about https://trello.com/c/ZM8JTvwJ, is for searching in the back office.

did 11:00
nope
perhaps it’s confusing but it’s not for the back-office (not only at least)

tap87 11:01
So, it is for the full site search. And is it going to be released in v3.1 or v4?

did 11:01
v3.2

**Comment by cappadona** [comment]
Thanks @tap87, any chance you got a rough time estimate on `v3.2` release so we know whether we need to work on a temporary stopgap for next month's usability testing?

**Comment by cappadona** [comment]
Just to clarify, we are implementing a temporary site search for the first round of usability. See #117.

**Comment by cappadona** [comment]
We no longer have a selectable search target. The search form queries only the Mann site, with a separate link for the Library Catalog.
