### ISSUE TITLE
Reservations only for all equipment

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#951]
No more first-come, first-serve (aka loanable) equipment. This will include the following modifications to the [equipment page](https://mannlib.cornell.edu/use/technology/equipment):

- [x] remove the **Pick up Now** buttons
- [x] remove the **Should I make a reservation?** callout
- [x] remove or trim down the policies to a common core
- [x] update the **Reserve** button link to go directly to one of the items within the category, not the category itself

Additionally, all individual pages for equipment categories will be dropped from the site to allow the equipment details to be managed solely in LibCal.

> Most likely will use the API to build the list of equipment (and links)

**Comment by cappadona** [comment]
@sew268 @eeh53 @tit1 I've taken a first pass at this and [deployed to dev](http://mannlib-dev.library.cornell.edu/locomotive/benevolent-drylands-8859/preview/use/technology/equipment).

A couple specific questions:
1. I tried keeping a somewhat trimmed-down policy list that could apply to all equipment, although I'm not sure about the fine amount. Should the policies stay or go?
1. The equipment list and URLs are built dynamically via the LibCal API. I also have access to the equipment details including images via the API. What does everyone think about a second pass with cards (a la SpaceFinder)?

> You'll see categories are missing since only those with active items are rendered. To get the rest to display, simply set at least one of the items within it **Active** from the LibCal admin 😄

**Comment by sew268** [comment]
Thanks @cappadona!  For your 1st question, I would be inclined to remove the policies from the website and have that be part of the reservation process in LibCal.  That said, I could also see the argument for having fine/fee policies on the website but I guess they are on CUL's website.  I'll defer to Tobi on this one.
For your 2nd question - yes!  I think cards for the equipment would be pretty sweet. :)

**Comment by cappadona** [comment]
@sew268 @eeh53 @tit1 [Policies have been dropped](http://mannlib-dev.library.cornell.edu/locomotive/benevolent-drylands-8859/preview/use/technology/equipment). Let me know once you're ready for me deploy to prod.

**Comment by cappadona** [comment]
P.S. I just created #958 in response to the interest in having cards for the equipment page

**Comment by eeh53** [comment]
@cappadona This looks pretty good. I think it's fine to remove the policies from the Mann page. I want to talk to @tit1 about a few things in LibCal before we make the rest of the equipment "active", but I think you can push these changes to production tomorrow.

**Comment by cappadona** [comment]
Got the green light from Tobi and Tom so this has been deployed to prod 😄
https://mannlib.cornell.edu/use/technology/equipment
