### ISSUE TITLE
Adjust reservations for spaces to handle Shibboleth Authentication

### ISSUE THREAD

**Issue by sew268** [cul-it/mann-wagon#967]
Remove widgets for study spaces and adjust all space reservations so that the experience mirrors the equipment reservations

**Comment by cappadona** [comment]
@sew268 Deployed to dev for your review. Please let me know if you have any questions.

**Comment by cappadona** [comment]
Thanks for reviewing & approving dev @sew268. Now deployed to production.

Once we confirm we're in good shape, we can try enabling Shibboleth again for the Mann location.

**Comment by cappadona** [comment]
@sew268 @eeh53 What's the latest on this? We still not ready to flip the switch on Shibboleth authentication for equipment and spaces reservations?

**Comment by cappadona** [comment]
Shibboleth authentication has been turned on for **all Mann spaces & equipment** as of today `2019-09-03`. Big thanks to my partners in crime, @jpm287 and @mrr15, who helped coordinate the logistics and line up undergrad and grad testers as well.

The **default behavior is to allow reservations from any patron with a valid NetID**. The following categories within Spaces have additional restrictions (only allowing reservations from students):

* [Individual Study Spaces](https://spaces.library.cornell.edu/spaces?lid=96&gid=5396)
* [Group Study Spaces](https://spaces.library.cornell.edu/spaces?lid=96&gid=4961)
* [Group Study Spaces (Limited Availability](https://spaces.library.cornell.edu/spaces?lid=96&gid=7491)
* [Collaborative Workstations](https://spaces.library.cornell.edu/spaces?lid=96&gid=7490)
* [Interview Room](https://spaces.library.cornell.edu/spaces?lid=96&gid=7492)

**Comment by cappadona** [comment]
Before and after screenshots of calling out restrictions on who can reserve individual study spaces. The same has been applied to Group Study Spaces. @sew268 & @eeh53 – please let me know if you'd like to do this consistently throughout any space or piece of equipment with reservation restrictions.

### Before

![Screenshot_2019-09-03 Space Availability - LibCal - Cornell University Library(1)](https://user-images.githubusercontent.com/409842/64204336-8f228880-ce63-11e9-91cf-eab054ee16d1.png)

### After

> [typo has been addressed](https://spaces.library.cornell.edu/spaces?lid=96&gid=5396)

![Screenshot_2019-09-03 Space Availability - LibCal - Cornell University Library](https://user-images.githubusercontent.com/409842/64204354-96e22d00-ce63-11e9-89ae-548431c34ddd.png)

**Comment by cappadona** [comment]
We've been running with this since the start of the Fall 2019 semester 😄
