### ISSUE TITLE
Automated nightly backups

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#97]
Cron job for DB backups via`mongodump`, saving to `S3` instance.

**Comment by cappadona** [comment]
##### Reference

* http://www.codeproject.com/Tips/547759/Automating-backup-for-MongoDB-using-CRON-and-S-CMD
* http://s3tools.org/s3cmd

**Comment by amccarty** [comment]
Another thought is to keep n dumps on disk and:

1. run dumps nightly
2. logrotate (compress, rotate n)
3. use s3cmd sync to copy diff to s3

**Comment by cappadona** [comment]
@amccarty Thanks, that sounds like a good approach.

**Comment by cappadona** [comment]
All set, thanks to Alan.
